# app/services/sam_gov_column_map.py — SAM.gov extract column mapping (Public V2)
#
# Generated from SAM_MASTER_EXTRACT_MAPPING_Feb2025.json — Public sensitivity_level only.
# Public V2 extract contains 142 fields per record (FOUO/Sensitive columns omitted).
# Do not edit manually — regenerate from the mapping JSON if schema changes.

from __future__ import annotations


SAM_GOV_COLUMNS: list[dict] = [
    {"v2_position": 1, "original_column_order": 1, "sam_field_name": 'UNIQUE ENTITY ID', "db_column_name": 'unique_entity_id', "datatype": 'STRING', "max_length": 12, "sensitivity_level": 'Public'},
    {"v2_position": 2, "original_column_order": 2, "sam_field_name": 'BLANK (DEPRECATED)', "db_column_name": 'col_002_deprecated', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 3, "original_column_order": 3, "sam_field_name": 'ENTITY EFT INDICATOR', "db_column_name": 'entity_eft_indicator', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 4, "original_column_order": 4, "sam_field_name": 'CAGE CODE', "db_column_name": 'cage_code', "datatype": 'STRING', "max_length": 5, "sensitivity_level": 'Public'},
    {"v2_position": 5, "original_column_order": 5, "sam_field_name": 'DODAAC', "db_column_name": 'dodaac', "datatype": 'STRING', "max_length": 9, "sensitivity_level": 'Public'},
    {"v2_position": 6, "original_column_order": 6, "sam_field_name": 'SAM EXTRACT CODE', "db_column_name": 'sam_extract_code', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"v2_position": 7, "original_column_order": 7, "sam_field_name": 'PURPOSE OF REGISTRATION', "db_column_name": 'purpose_of_registration', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'Public'},
    {"v2_position": 8, "original_column_order": 8, "sam_field_name": 'INITIAL REGISTRATION DATE', "db_column_name": 'initial_registration_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Public'},
    {"v2_position": 9, "original_column_order": 9, "sam_field_name": 'REGISTRATION EXPIRATION DATE', "db_column_name": 'registration_expiration_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Public'},
    {"v2_position": 10, "original_column_order": 10, "sam_field_name": 'LAST UPDATE DATE', "db_column_name": 'last_update_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Public'},
    {"v2_position": 11, "original_column_order": 11, "sam_field_name": 'ACTIVATION DATE', "db_column_name": 'activation_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Public'},
    {"v2_position": 12, "original_column_order": 12, "sam_field_name": 'LEGAL BUSINESS NAME', "db_column_name": 'legal_business_name', "datatype": 'STRING', "max_length": 120, "sensitivity_level": 'Public'},
    {"v2_position": 13, "original_column_order": 13, "sam_field_name": 'DBA NAME', "db_column_name": 'dba_name', "datatype": 'STRING', "max_length": 120, "sensitivity_level": 'Public'},
    {"v2_position": 14, "original_column_order": 14, "sam_field_name": 'ENTITY DIVISION NAME', "db_column_name": 'entity_division_name', "datatype": 'STRING', "max_length": 60, "sensitivity_level": 'Public'},
    {"v2_position": 15, "original_column_order": 15, "sam_field_name": 'ENTITY DIVISION NUMBER', "db_column_name": 'entity_division_number', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'Public'},
    {"v2_position": 16, "original_column_order": 16, "sam_field_name": 'PHYSICAL ADDRESS LINE 1', "db_column_name": 'physical_address_line_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 17, "original_column_order": 17, "sam_field_name": 'PHYSICAL ADDRESS LINE 2', "db_column_name": 'physical_address_line_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 18, "original_column_order": 18, "sam_field_name": 'PHYSICAL ADDRESS CITY', "db_column_name": 'physical_address_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"v2_position": 19, "original_column_order": 19, "sam_field_name": 'PHYSICAL ADDRESS PROVINCE OR STATE', "db_column_name": 'physical_address_province_or_state', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"v2_position": 20, "original_column_order": 20, "sam_field_name": 'PHYSICAL ADDRESS ZIP/POSTAL CODE', "db_column_name": 'physical_address_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 21, "original_column_order": 21, "sam_field_name": 'PHYSICAL ADDRESS ZIP CODE +4', "db_column_name": 'physical_address_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 22, "original_column_order": 22, "sam_field_name": 'PHYSICAL ADDRESS COUNTRY CODE', "db_column_name": 'physical_address_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 23, "original_column_order": 23, "sam_field_name": 'PHYSICAL ADDRESS CONGRESSIONAL DISTRICT', "db_column_name": 'physical_address_congressional_district', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'Public'},
    {"v2_position": 24, "original_column_order": 24, "sam_field_name": 'D&B OPEN DATA FLAG', "db_column_name": 'db_open_data_flag', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"v2_position": 25, "original_column_order": 25, "sam_field_name": 'ENTITY START DATE', "db_column_name": 'entity_start_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Public'},
    {"v2_position": 26, "original_column_order": 26, "sam_field_name": 'FISCAL YEAR END CLOSE DATE', "db_column_name": 'fiscal_year_end_close_date', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 27, "original_column_order": 29, "sam_field_name": 'ENTITY URL', "db_column_name": 'entity_url', "datatype": 'STRING', "max_length": 200, "sensitivity_level": 'Public'},
    {"v2_position": 28, "original_column_order": 30, "sam_field_name": 'ENTITY STRUCTURE', "db_column_name": 'entity_structure', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'Public'},
    {"v2_position": 29, "original_column_order": 31, "sam_field_name": 'STATE OF INCORPORATION', "db_column_name": 'state_of_incorporation', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'Public'},
    {"v2_position": 30, "original_column_order": 32, "sam_field_name": 'COUNTRY OF INCORPORATION', "db_column_name": 'country_of_incorporation', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 31, "original_column_order": 33, "sam_field_name": 'BUSINESS TYPE COUNTER', "db_column_name": 'business_type_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 32, "original_column_order": 34, "sam_field_name": 'BUS TYPE STRING', "db_column_name": 'bus_type_string', "datatype": 'STRING', "max_length": 220, "sensitivity_level": 'Public'},
    {"v2_position": 33, "original_column_order": 36, "sam_field_name": 'PRIMARY NAICS', "db_column_name": 'primary_naics', "datatype": 'STRING', "max_length": 6, "sensitivity_level": 'Public'},
    {"v2_position": 34, "original_column_order": 37, "sam_field_name": 'NAICS CODE COUNTER', "db_column_name": 'naics_code_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 35, "original_column_order": 38, "sam_field_name": 'NAICS CODE STRING', "db_column_name": 'naics_code_string', "datatype": 'STRING', "max_length": 12000, "sensitivity_level": 'Public'},
    {"v2_position": 36, "original_column_order": 39, "sam_field_name": 'PSC CODE COUNTER', "db_column_name": 'psc_code_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 37, "original_column_order": 40, "sam_field_name": 'PSC CODE STRING', "db_column_name": 'psc_code_string', "datatype": 'STRING', "max_length": 2500, "sensitivity_level": 'Public'},
    {"v2_position": 38, "original_column_order": 41, "sam_field_name": 'CREDIT CARD USAGE', "db_column_name": 'credit_card_usage', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"v2_position": 39, "original_column_order": 42, "sam_field_name": 'CORRESPONDENCE FLAG', "db_column_name": 'correspondence_flag', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"v2_position": 40, "original_column_order": 43, "sam_field_name": 'MAILING ADDRESS LINE 1', "db_column_name": 'mailing_address_line_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 41, "original_column_order": 44, "sam_field_name": 'MAILING ADDRESS LINE 2', "db_column_name": 'mailing_address_line_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 42, "original_column_order": 45, "sam_field_name": 'MAILING ADDRESS CITY', "db_column_name": 'mailing_address_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"v2_position": 43, "original_column_order": 46, "sam_field_name": 'MAILING ADDRESS ZIP/POSTAL CODE', "db_column_name": 'mailing_address_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 44, "original_column_order": 47, "sam_field_name": 'MAILING ADDRESS ZIP CODE +4', "db_column_name": 'mailing_address_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 45, "original_column_order": 48, "sam_field_name": 'MAILING ADDRESS COUNTRY', "db_column_name": 'mailing_address_country', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 46, "original_column_order": 49, "sam_field_name": 'MAILING ADDRESS STATE OR PROVINCE', "db_column_name": 'mailing_address_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"v2_position": 47, "original_column_order": 50, "sam_field_name": 'GOVT BUS POC FIRST NAME', "db_column_name": 'govt_bus_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 48, "original_column_order": 51, "sam_field_name": 'GOVT BUS POC MIDDLE INITIAL', "db_column_name": 'govt_bus_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 49, "original_column_order": 52, "sam_field_name": 'GOVT BUS POC LAST NAME', "db_column_name": 'govt_bus_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 50, "original_column_order": 53, "sam_field_name": 'GOVT BUS POC TITLE', "db_column_name": 'govt_bus_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 51, "original_column_order": 54, "sam_field_name": 'GOVT BUS POC ST ADD 1', "db_column_name": 'govt_bus_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 52, "original_column_order": 55, "sam_field_name": 'GOVT BUS POC ST ADD 2', "db_column_name": 'govt_bus_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 53, "original_column_order": 56, "sam_field_name": 'GOVT BUS POC CITY', "db_column_name": 'govt_bus_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"v2_position": 54, "original_column_order": 57, "sam_field_name": 'GOVT BUS POC ZIP/POSTAL CODE', "db_column_name": 'govt_bus_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 55, "original_column_order": 58, "sam_field_name": 'GOVT BUS POC ZIP CODE +4', "db_column_name": 'govt_bus_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 56, "original_column_order": 59, "sam_field_name": 'GOVT BUS POC COUNTRY CODE', "db_column_name": 'govt_bus_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 57, "original_column_order": 60, "sam_field_name": 'GOVT BUS POC STATE OR PROVINCE', "db_column_name": 'govt_bus_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"v2_position": 58, "original_column_order": 66, "sam_field_name": 'ALT GOVT BUS POC FIRST NAME', "db_column_name": 'alt_govt_bus_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 59, "original_column_order": 67, "sam_field_name": 'ALT GOVT BUS POC MIDDLE INITIAL', "db_column_name": 'alt_govt_bus_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 60, "original_column_order": 68, "sam_field_name": 'ALT GOVT BUS POC LAST NAME', "db_column_name": 'alt_govt_bus_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 61, "original_column_order": 69, "sam_field_name": 'ALT GOVT BUS POC TITLE', "db_column_name": 'alt_govt_bus_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 62, "original_column_order": 70, "sam_field_name": 'ALT GOVT BUS POC ST ADD 1', "db_column_name": 'alt_govt_bus_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 63, "original_column_order": 71, "sam_field_name": 'ALT GOVT BUS POC ST ADD 2', "db_column_name": 'alt_govt_bus_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 64, "original_column_order": 72, "sam_field_name": 'ALT GOVT BUS POC CITY', "db_column_name": 'alt_govt_bus_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"v2_position": 65, "original_column_order": 73, "sam_field_name": 'ALT GOVT BUS POC ZIP/POSTAL CODE', "db_column_name": 'alt_govt_bus_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 66, "original_column_order": 74, "sam_field_name": 'ALT GOVT BUS POC ZIP CODE +4', "db_column_name": 'alt_govt_bus_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 67, "original_column_order": 75, "sam_field_name": 'ALT GOVT BUS POC COUNTRY CODE', "db_column_name": 'alt_govt_bus_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 68, "original_column_order": 76, "sam_field_name": 'ALT GOVT BUS POC STATE OR PROVINCE', "db_column_name": 'alt_govt_bus_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"v2_position": 69, "original_column_order": 82, "sam_field_name": 'PAST PERF POC POC  FIRST NAME', "db_column_name": 'past_perf_poc_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 70, "original_column_order": 83, "sam_field_name": 'PAST PERF POC POC  MIDDLE INITIAL', "db_column_name": 'past_perf_poc_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 71, "original_column_order": 84, "sam_field_name": 'PAST PERF POC POC  LAST NAME', "db_column_name": 'past_perf_poc_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 72, "original_column_order": 85, "sam_field_name": 'PAST PERF POC POC  TITLE', "db_column_name": 'past_perf_poc_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 73, "original_column_order": 86, "sam_field_name": 'PAST PERF POC ST ADD 1', "db_column_name": 'past_perf_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 74, "original_column_order": 87, "sam_field_name": 'PAST PERF POC ST ADD 2', "db_column_name": 'past_perf_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 75, "original_column_order": 88, "sam_field_name": 'PAST PERF POC CITY', "db_column_name": 'past_perf_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"v2_position": 76, "original_column_order": 89, "sam_field_name": 'PAST PERF POC ZIP/POSTAL CODE', "db_column_name": 'past_perf_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 77, "original_column_order": 90, "sam_field_name": 'PAST PERF POC ZIP CODE +4', "db_column_name": 'past_perf_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 78, "original_column_order": 91, "sam_field_name": 'PAST PERF POC COUNTRY CODE', "db_column_name": 'past_perf_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 79, "original_column_order": 92, "sam_field_name": 'PAST PERF POC STATE OR PROVINCE', "db_column_name": 'past_perf_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"v2_position": 80, "original_column_order": 98, "sam_field_name": 'ALT PAST PERF POC FIRST NAME', "db_column_name": 'alt_past_perf_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 81, "original_column_order": 99, "sam_field_name": 'ALT PAST PERF POC MIDDLE INITIAL', "db_column_name": 'alt_past_perf_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 82, "original_column_order": 100, "sam_field_name": 'ALT PAST PERF POC LAST NAME', "db_column_name": 'alt_past_perf_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 83, "original_column_order": 101, "sam_field_name": 'ALT PAST PERF POC TITLE', "db_column_name": 'alt_past_perf_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 84, "original_column_order": 102, "sam_field_name": 'ALT PAST PERF POC ST ADD 1', "db_column_name": 'alt_past_perf_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 85, "original_column_order": 103, "sam_field_name": 'ALT PAST PERF POC ST ADD 2', "db_column_name": 'alt_past_perf_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 86, "original_column_order": 104, "sam_field_name": 'ALT PAST PERF POC CITY', "db_column_name": 'alt_past_perf_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"v2_position": 87, "original_column_order": 105, "sam_field_name": 'ALT PAST PERF POC ZIP/POSTAL CODE', "db_column_name": 'alt_past_perf_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 88, "original_column_order": 106, "sam_field_name": 'ALT PAST PERF POC ZIP CODE +4', "db_column_name": 'alt_past_perf_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 89, "original_column_order": 107, "sam_field_name": 'ALT PAST PERF POC COUNTRY CODE', "db_column_name": 'alt_past_perf_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 90, "original_column_order": 108, "sam_field_name": 'ALT PAST PERF POC STATE OR PROVINCE', "db_column_name": 'alt_past_perf_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"v2_position": 91, "original_column_order": 114, "sam_field_name": 'ELEC BUS POC FIRST NAME', "db_column_name": 'elec_bus_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 92, "original_column_order": 115, "sam_field_name": 'ELEC BUS POC MIDDLE INITIAL', "db_column_name": 'elec_bus_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 93, "original_column_order": 116, "sam_field_name": 'ELEC BUS POC LAST NAME', "db_column_name": 'elec_bus_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 94, "original_column_order": 117, "sam_field_name": 'ELEC BUS POC TITLE', "db_column_name": 'elec_bus_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 95, "original_column_order": 118, "sam_field_name": 'ELEC BUS POC ST ADD 1', "db_column_name": 'elec_bus_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 96, "original_column_order": 119, "sam_field_name": 'ELEC BUS POC ST ADD 2', "db_column_name": 'elec_bus_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 97, "original_column_order": 120, "sam_field_name": 'ELEC BUS POC CITY', "db_column_name": 'elec_bus_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"v2_position": 98, "original_column_order": 121, "sam_field_name": 'ELEC BUS POC ZIP/POSTAL CODE', "db_column_name": 'elec_bus_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 99, "original_column_order": 122, "sam_field_name": 'ELEC BUS POC ZIP CODE +4', "db_column_name": 'elec_bus_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 100, "original_column_order": 123, "sam_field_name": 'ELEC BUS POC COUNTRY CODE', "db_column_name": 'elec_bus_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 101, "original_column_order": 124, "sam_field_name": 'ELEC BUS POC STATE OR PROVINCE', "db_column_name": 'elec_bus_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"v2_position": 102, "original_column_order": 130, "sam_field_name": 'ALT ELEC POC BUS POC FIRST NAME', "db_column_name": 'alt_elec_poc_bus_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 103, "original_column_order": 131, "sam_field_name": 'ALT ELEC POC BUS POC MIDDLE INITIAL', "db_column_name": 'alt_elec_poc_bus_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 104, "original_column_order": 132, "sam_field_name": 'ALT ELEC POC BUS POC LAST NAME', "db_column_name": 'alt_elec_poc_bus_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"v2_position": 105, "original_column_order": 133, "sam_field_name": 'ALT ELEC POC BUS POC TITLE', "db_column_name": 'alt_elec_poc_bus_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 106, "original_column_order": 134, "sam_field_name": 'ALT ELEC POC BUS ST ADD 1', "db_column_name": 'alt_elec_poc_bus_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 107, "original_column_order": 135, "sam_field_name": 'ALT ELEC POC BUS ST ADD 2', "db_column_name": 'alt_elec_poc_bus_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"v2_position": 108, "original_column_order": 136, "sam_field_name": 'ALT ELEC POC BUS CITY', "db_column_name": 'alt_elec_poc_bus_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"v2_position": 109, "original_column_order": 137, "sam_field_name": 'ALT ELEC POC BUS ZIP/POSTAL CODE', "db_column_name": 'alt_elec_poc_bus_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"v2_position": 110, "original_column_order": 138, "sam_field_name": 'ALT ELEC POC BUS ZIP CODE +4', "db_column_name": 'alt_elec_poc_bus_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 111, "original_column_order": 139, "sam_field_name": 'ALT ELEC POC BUS COUNTRY CODE', "db_column_name": 'alt_elec_poc_bus_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 112, "original_column_order": 140, "sam_field_name": 'ALT ELEC POC BUS STATE OR PROVINCE', "db_column_name": 'alt_elec_poc_bus_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"v2_position": 113, "original_column_order": 285, "sam_field_name": 'NAICS EXCEPTION COUNTER', "db_column_name": 'naics_exception_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 114, "original_column_order": 286, "sam_field_name": 'NAICS EXCEPTION STRING', "db_column_name": 'naics_exception_string', "datatype": 'STRING', "max_length": 1100, "sensitivity_level": 'Public'},
    {"v2_position": 115, "original_column_order": 287, "sam_field_name": 'DEBT SUBJECT TO OFFSET FLAG', "db_column_name": 'debt_subject_to_offset_flag', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"v2_position": 116, "original_column_order": 288, "sam_field_name": 'EXCLUSION STATUS FLAG', "db_column_name": 'exclusion_status_flag', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"v2_position": 117, "original_column_order": 289, "sam_field_name": 'SBA BUSINESS TYPES COUNTER', "db_column_name": 'sba_business_types_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 118, "original_column_order": 290, "sam_field_name": 'SBA BUSINESS TYPES STRING', "db_column_name": 'sba_business_types_string', "datatype": 'STRING', "max_length": 125, "sensitivity_level": 'Public'},
    {"v2_position": 119, "original_column_order": 293, "sam_field_name": 'NO PUBLIC DISPLAY FLAG', "db_column_name": 'no_public_display_flag', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 120, "original_column_order": 294, "sam_field_name": 'DISASTER RESPONSE COUNTER', "db_column_name": 'disaster_response_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 121, "original_column_order": 295, "sam_field_name": 'DISASTER RESPONSE STRING', "db_column_name": 'disaster_response_string', "datatype": 'STRING', "max_length": 75, "sensitivity_level": 'Public'},
    {"v2_position": 122, "original_column_order": 342, "sam_field_name": 'ENTITY EVS SOURCE', "db_column_name": 'entity_evs_source', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'Public'},
    {"v2_position": 123, "original_column_order": 347, "sam_field_name": 'FLEX FIELD 6', "db_column_name": 'flex_field_6', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 124, "original_column_order": 348, "sam_field_name": 'FLEX FIELD 7', "db_column_name": 'flex_field_7', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 125, "original_column_order": 349, "sam_field_name": 'FLEX FIELD 8', "db_column_name": 'flex_field_8', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 126, "original_column_order": 350, "sam_field_name": 'FLEX FIELD 9', "db_column_name": 'flex_field_9', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 127, "original_column_order": 351, "sam_field_name": 'FLEX FIELD 10', "db_column_name": 'flex_field_10', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 128, "original_column_order": 352, "sam_field_name": 'FLEX FIELD 11', "db_column_name": 'flex_field_11', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 129, "original_column_order": 353, "sam_field_name": 'FLEX FIELD 12', "db_column_name": 'flex_field_12', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 130, "original_column_order": 354, "sam_field_name": 'FLEX FIELD 13', "db_column_name": 'flex_field_13', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 131, "original_column_order": 355, "sam_field_name": 'FLEX FIELD 14', "db_column_name": 'flex_field_14', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 132, "original_column_order": 356, "sam_field_name": 'FLEX FIELD 15', "db_column_name": 'flex_field_15', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 133, "original_column_order": 357, "sam_field_name": 'FLEX FIELD 16', "db_column_name": 'flex_field_16', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 134, "original_column_order": 358, "sam_field_name": 'FLEX FIELD 17', "db_column_name": 'flex_field_17', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 135, "original_column_order": 359, "sam_field_name": 'FLEX FIELD 18', "db_column_name": 'flex_field_18', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 136, "original_column_order": 360, "sam_field_name": 'FLEX FIELD 19', "db_column_name": 'flex_field_19', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 137, "original_column_order": 361, "sam_field_name": 'FLEX FIELD 20', "db_column_name": 'flex_field_20', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"v2_position": 138, "original_column_order": None, "sam_field_name": 'FLEX FIELD 21', "db_column_name": 'flex_field_21', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"v2_position": 139, "original_column_order": None, "sam_field_name": 'FLEX FIELD 22', "db_column_name": 'flex_field_22', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'Public'},
    {"v2_position": 140, "original_column_order": None, "sam_field_name": 'FLEX FIELD 23', "db_column_name": 'flex_field_23', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"v2_position": 141, "original_column_order": None, "sam_field_name": 'FLEX FIELD 24', "db_column_name": 'flex_field_24', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"v2_position": 142, "original_column_order": 362, "sam_field_name": 'END OF RECORD INDICATOR', "db_column_name": 'end_of_record_indicator', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
]


SAM_GOV_COLUMN_COUNT: int = len(SAM_GOV_COLUMNS)

SAM_GOV_DB_COLUMN_NAMES: list[str] = [col['db_column_name'] for col in SAM_GOV_COLUMNS]


# ── Self-test ──────────────────────────────────────────────────────────────

if __name__ == '__main__':
    assert SAM_GOV_COLUMN_COUNT == 142, f'Expected 142 columns, got {SAM_GOV_COLUMN_COUNT}'
    assert SAM_GOV_COLUMNS[0]['db_column_name'] == 'unique_entity_id'
    assert SAM_GOV_COLUMNS[-1]['db_column_name'] == 'end_of_record_indicator'
    assert len(set(SAM_GOV_DB_COLUMN_NAMES)) == 142, 'Duplicate db column names'
    print(f'SAM.gov Public V2 column map: {SAM_GOV_COLUMN_COUNT} columns OK')
    print(f'  First: {SAM_GOV_COLUMNS[0]["db_column_name"]}')
    print(f'  Last:  {SAM_GOV_COLUMNS[-1]["db_column_name"]}')

