# app/services/sam_gov_column_map.py — SAM.gov extract column mapping
#
# Generated from SAM_MASTER_EXTRACT_MAPPING_Feb2025.json
# Do not edit manually — regenerate from the mapping JSON if schema changes.

from __future__ import annotations


SAM_GOV_COLUMNS: list[dict] = [
    {"position": 1, "sam_field_name": 'UNIQUE ENTITY ID', "db_column_name": 'unique_entity_id', "datatype": 'STRING', "max_length": 12, "sensitivity_level": 'Public'},
    {"position": 2, "sam_field_name": 'BLANK (DEPRECATED)', "db_column_name": 'col_002_deprecated', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 3, "sam_field_name": 'ENTITY EFT INDICATOR', "db_column_name": 'entity_eft_indicator', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 4, "sam_field_name": 'CAGE CODE', "db_column_name": 'cage_code', "datatype": 'STRING', "max_length": 5, "sensitivity_level": 'Public'},
    {"position": 5, "sam_field_name": 'DODAAC', "db_column_name": 'dodaac', "datatype": 'STRING', "max_length": 9, "sensitivity_level": 'Public'},
    {"position": 6, "sam_field_name": 'SAM EXTRACT CODE', "db_column_name": 'sam_extract_code', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"position": 7, "sam_field_name": 'PURPOSE OF REGISTRATION', "db_column_name": 'purpose_of_registration', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'Public'},
    {"position": 8, "sam_field_name": 'INITIAL REGISTRATION DATE', "db_column_name": 'initial_registration_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Public'},
    {"position": 9, "sam_field_name": 'REGISTRATION EXPIRATION DATE', "db_column_name": 'registration_expiration_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Public'},
    {"position": 10, "sam_field_name": 'LAST UPDATE DATE', "db_column_name": 'last_update_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Public'},
    {"position": 11, "sam_field_name": 'ACTIVATION DATE', "db_column_name": 'activation_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Public'},
    {"position": 12, "sam_field_name": 'LEGAL BUSINESS NAME', "db_column_name": 'legal_business_name', "datatype": 'STRING', "max_length": 120, "sensitivity_level": 'Public'},
    {"position": 13, "sam_field_name": 'DBA NAME', "db_column_name": 'dba_name', "datatype": 'STRING', "max_length": 120, "sensitivity_level": 'Public'},
    {"position": 14, "sam_field_name": 'ENTITY DIVISION NAME', "db_column_name": 'entity_division_name', "datatype": 'STRING', "max_length": 60, "sensitivity_level": 'Public'},
    {"position": 15, "sam_field_name": 'ENTITY DIVISION NUMBER', "db_column_name": 'entity_division_number', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'Public'},
    {"position": 16, "sam_field_name": 'PHYSICAL ADDRESS LINE 1', "db_column_name": 'physical_address_line_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 17, "sam_field_name": 'PHYSICAL ADDRESS LINE 2', "db_column_name": 'physical_address_line_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 18, "sam_field_name": 'PHYSICAL ADDRESS CITY', "db_column_name": 'physical_address_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"position": 19, "sam_field_name": 'PHYSICAL ADDRESS PROVINCE OR STATE', "db_column_name": 'physical_address_province_or_state', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"position": 20, "sam_field_name": 'PHYSICAL ADDRESS ZIP/POSTAL CODE', "db_column_name": 'physical_address_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 21, "sam_field_name": 'PHYSICAL ADDRESS ZIP CODE +4', "db_column_name": 'physical_address_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 22, "sam_field_name": 'PHYSICAL ADDRESS COUNTRY CODE', "db_column_name": 'physical_address_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 23, "sam_field_name": 'PHYSICAL ADDRESS CONGRESSIONAL DISTRICT', "db_column_name": 'physical_address_congressional_district', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'Public'},
    {"position": 24, "sam_field_name": 'D&B OPEN DATA FLAG', "db_column_name": 'db_open_data_flag', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"position": 25, "sam_field_name": 'ENTITY START DATE', "db_column_name": 'entity_start_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Public'},
    {"position": 26, "sam_field_name": 'FISCAL YEAR END CLOSE DATE', "db_column_name": 'fiscal_year_end_close_date', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 27, "sam_field_name": 'COMPANY SECURITY LEVEL', "db_column_name": 'company_security_level', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 28, "sam_field_name": 'HIGHEST EMPLOYEE SECURITY LEVEL', "db_column_name": 'highest_employee_security_level', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 29, "sam_field_name": 'ENTITY URL', "db_column_name": 'entity_url', "datatype": 'STRING', "max_length": 200, "sensitivity_level": 'Public'},
    {"position": 30, "sam_field_name": 'ENTITY STRUCTURE', "db_column_name": 'entity_structure', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'Public'},
    {"position": 31, "sam_field_name": 'STATE OF INCORPORATION', "db_column_name": 'state_of_incorporation', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'Public'},
    {"position": 32, "sam_field_name": 'COUNTRY OF INCORPORATION', "db_column_name": 'country_of_incorporation', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 33, "sam_field_name": 'BUSINESS TYPE COUNTER', "db_column_name": 'business_type_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 34, "sam_field_name": 'BUS TYPE STRING', "db_column_name": 'bus_type_string', "datatype": 'STRING', "max_length": 220, "sensitivity_level": 'Public'},
    {"position": 35, "sam_field_name": 'AGENCY BUSINESS PURPOSE', "db_column_name": 'agency_business_purpose', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 36, "sam_field_name": 'PRIMARY NAICS', "db_column_name": 'primary_naics', "datatype": 'STRING', "max_length": 6, "sensitivity_level": 'Public'},
    {"position": 37, "sam_field_name": 'NAICS CODE COUNTER', "db_column_name": 'naics_code_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 38, "sam_field_name": 'NAICS CODE STRING', "db_column_name": 'naics_code_string', "datatype": 'STRING', "max_length": 12000, "sensitivity_level": 'Public'},
    {"position": 39, "sam_field_name": 'PSC CODE COUNTER', "db_column_name": 'psc_code_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 40, "sam_field_name": 'PSC CODE STRING', "db_column_name": 'psc_code_string', "datatype": 'STRING', "max_length": 2500, "sensitivity_level": 'Public'},
    {"position": 41, "sam_field_name": 'CREDIT CARD USAGE', "db_column_name": 'credit_card_usage', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"position": 42, "sam_field_name": 'CORRESPONDENCE FLAG', "db_column_name": 'correspondence_flag', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"position": 43, "sam_field_name": 'MAILING ADDRESS LINE 1', "db_column_name": 'mailing_address_line_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 44, "sam_field_name": 'MAILING ADDRESS LINE 2', "db_column_name": 'mailing_address_line_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 45, "sam_field_name": 'MAILING ADDRESS CITY', "db_column_name": 'mailing_address_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"position": 46, "sam_field_name": 'MAILING ADDRESS ZIP/POSTAL CODE', "db_column_name": 'mailing_address_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 47, "sam_field_name": 'MAILING ADDRESS ZIP CODE +4', "db_column_name": 'mailing_address_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 48, "sam_field_name": 'MAILING ADDRESS COUNTRY', "db_column_name": 'mailing_address_country', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 49, "sam_field_name": 'MAILING ADDRESS STATE OR PROVINCE', "db_column_name": 'mailing_address_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"position": 50, "sam_field_name": 'GOVT BUS POC FIRST NAME', "db_column_name": 'govt_bus_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 51, "sam_field_name": 'GOVT BUS POC MIDDLE INITIAL', "db_column_name": 'govt_bus_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 52, "sam_field_name": 'GOVT BUS POC LAST NAME', "db_column_name": 'govt_bus_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 53, "sam_field_name": 'GOVT BUS POC TITLE', "db_column_name": 'govt_bus_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 54, "sam_field_name": 'GOVT BUS POC ST ADD 1', "db_column_name": 'govt_bus_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 55, "sam_field_name": 'GOVT BUS POC ST ADD 2', "db_column_name": 'govt_bus_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 56, "sam_field_name": 'GOVT BUS POC CITY', "db_column_name": 'govt_bus_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"position": 57, "sam_field_name": 'GOVT BUS POC ZIP/POSTAL CODE', "db_column_name": 'govt_bus_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 58, "sam_field_name": 'GOVT BUS POC ZIP CODE +4', "db_column_name": 'govt_bus_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 59, "sam_field_name": 'GOVT BUS POC COUNTRY CODE', "db_column_name": 'govt_bus_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 60, "sam_field_name": 'GOVT BUS POC STATE OR PROVINCE', "db_column_name": 'govt_bus_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"position": 61, "sam_field_name": 'GOVT BUS POC U.S. PHONE', "db_column_name": 'govt_bus_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 62, "sam_field_name": 'GOVT BUS POC U.S. PHONE EXT', "db_column_name": 'govt_bus_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 63, "sam_field_name": 'GOVT BUS POC NON-U.S. PHONE', "db_column_name": 'govt_bus_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 64, "sam_field_name": 'GOVT BUS POC FAX U.S. ONLY', "db_column_name": 'govt_bus_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 65, "sam_field_name": 'GOVT BUS POC EMAIL', "db_column_name": 'govt_bus_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 66, "sam_field_name": 'ALT GOVT BUS POC FIRST NAME', "db_column_name": 'alt_govt_bus_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 67, "sam_field_name": 'ALT GOVT BUS POC MIDDLE INITIAL', "db_column_name": 'alt_govt_bus_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 68, "sam_field_name": 'ALT GOVT BUS POC LAST NAME', "db_column_name": 'alt_govt_bus_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 69, "sam_field_name": 'ALT GOVT BUS POC TITLE', "db_column_name": 'alt_govt_bus_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 70, "sam_field_name": 'ALT GOVT BUS POC ST ADD 1', "db_column_name": 'alt_govt_bus_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 71, "sam_field_name": 'ALT GOVT BUS POC ST ADD 2', "db_column_name": 'alt_govt_bus_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 72, "sam_field_name": 'ALT GOVT BUS POC CITY', "db_column_name": 'alt_govt_bus_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"position": 73, "sam_field_name": 'ALT GOVT BUS POC ZIP/POSTAL CODE', "db_column_name": 'alt_govt_bus_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 74, "sam_field_name": 'ALT GOVT BUS POC ZIP CODE +4', "db_column_name": 'alt_govt_bus_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 75, "sam_field_name": 'ALT GOVT BUS POC COUNTRY CODE', "db_column_name": 'alt_govt_bus_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 76, "sam_field_name": 'ALT GOVT BUS POC STATE OR PROVINCE', "db_column_name": 'alt_govt_bus_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"position": 77, "sam_field_name": 'ALT GOVT BUS POC U.S. PHONE', "db_column_name": 'alt_govt_bus_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 78, "sam_field_name": 'ALT GOVT BUS POC U.S. PHONE EXT', "db_column_name": 'alt_govt_bus_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 79, "sam_field_name": 'ALT GOVT BUS POC NON-U.S. PHONE', "db_column_name": 'alt_govt_bus_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 80, "sam_field_name": 'ALT GOVT BUS POC FAX U.S. ONLY', "db_column_name": 'alt_govt_bus_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 81, "sam_field_name": 'ALT GOVT BUS POC EMAIL', "db_column_name": 'alt_govt_bus_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 82, "sam_field_name": 'PAST PERF POC POC  FIRST NAME', "db_column_name": 'past_perf_poc_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 83, "sam_field_name": 'PAST PERF POC POC  MIDDLE INITIAL', "db_column_name": 'past_perf_poc_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 84, "sam_field_name": 'PAST PERF POC POC  LAST NAME', "db_column_name": 'past_perf_poc_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 85, "sam_field_name": 'PAST PERF POC POC  TITLE', "db_column_name": 'past_perf_poc_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 86, "sam_field_name": 'PAST PERF POC ST ADD 1', "db_column_name": 'past_perf_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 87, "sam_field_name": 'PAST PERF POC ST ADD 2', "db_column_name": 'past_perf_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 88, "sam_field_name": 'PAST PERF POC CITY', "db_column_name": 'past_perf_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"position": 89, "sam_field_name": 'PAST PERF POC ZIP/POSTAL CODE', "db_column_name": 'past_perf_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 90, "sam_field_name": 'PAST PERF POC ZIP CODE +4', "db_column_name": 'past_perf_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 91, "sam_field_name": 'PAST PERF POC COUNTRY CODE', "db_column_name": 'past_perf_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 92, "sam_field_name": 'PAST PERF POC STATE OR PROVINCE', "db_column_name": 'past_perf_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"position": 93, "sam_field_name": 'PAST PERF POC U.S. PHONE', "db_column_name": 'past_perf_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 94, "sam_field_name": 'PAST PERF POC U.S. PHONE EXT', "db_column_name": 'past_perf_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 95, "sam_field_name": 'PAST PERF POC NON-U.S. PHONE', "db_column_name": 'past_perf_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 96, "sam_field_name": 'PAST PERF POC FAX U.S. ONLY', "db_column_name": 'past_perf_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 97, "sam_field_name": 'PAST PERF POC EMAIL', "db_column_name": 'past_perf_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 98, "sam_field_name": 'ALT PAST PERF POC FIRST NAME', "db_column_name": 'alt_past_perf_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 99, "sam_field_name": 'ALT PAST PERF POC MIDDLE INITIAL', "db_column_name": 'alt_past_perf_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 100, "sam_field_name": 'ALT PAST PERF POC LAST NAME', "db_column_name": 'alt_past_perf_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 101, "sam_field_name": 'ALT PAST PERF POC TITLE', "db_column_name": 'alt_past_perf_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 102, "sam_field_name": 'ALT PAST PERF POC ST ADD 1', "db_column_name": 'alt_past_perf_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 103, "sam_field_name": 'ALT PAST PERF POC ST ADD 2', "db_column_name": 'alt_past_perf_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 104, "sam_field_name": 'ALT PAST PERF POC CITY', "db_column_name": 'alt_past_perf_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"position": 105, "sam_field_name": 'ALT PAST PERF POC ZIP/POSTAL CODE', "db_column_name": 'alt_past_perf_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 106, "sam_field_name": 'ALT PAST PERF POC ZIP CODE +4', "db_column_name": 'alt_past_perf_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 107, "sam_field_name": 'ALT PAST PERF POC COUNTRY CODE', "db_column_name": 'alt_past_perf_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 108, "sam_field_name": 'ALT PAST PERF POC STATE OR PROVINCE', "db_column_name": 'alt_past_perf_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"position": 109, "sam_field_name": 'ALT PAST PERF POC U.S. PHONE', "db_column_name": 'alt_past_perf_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 110, "sam_field_name": 'ALT PAST PERF POC U.S. PHONE EXT', "db_column_name": 'alt_past_perf_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 111, "sam_field_name": 'ALT PAST PERF POC NON-U.S. PHONE', "db_column_name": 'alt_past_perf_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 112, "sam_field_name": 'ALT PAST PERF POC FAX U.S. ONLY', "db_column_name": 'alt_past_perf_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 113, "sam_field_name": 'ALT PAST PERF POC EMAIL', "db_column_name": 'alt_past_perf_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 114, "sam_field_name": 'ELEC BUS POC FIRST NAME', "db_column_name": 'elec_bus_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 115, "sam_field_name": 'ELEC BUS POC MIDDLE INITIAL', "db_column_name": 'elec_bus_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 116, "sam_field_name": 'ELEC BUS POC LAST NAME', "db_column_name": 'elec_bus_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 117, "sam_field_name": 'ELEC BUS POC TITLE', "db_column_name": 'elec_bus_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 118, "sam_field_name": 'ELEC BUS POC ST ADD 1', "db_column_name": 'elec_bus_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 119, "sam_field_name": 'ELEC BUS POC ST ADD 2', "db_column_name": 'elec_bus_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 120, "sam_field_name": 'ELEC BUS POC CITY', "db_column_name": 'elec_bus_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"position": 121, "sam_field_name": 'ELEC BUS POC ZIP/POSTAL CODE', "db_column_name": 'elec_bus_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 122, "sam_field_name": 'ELEC BUS POC ZIP CODE +4', "db_column_name": 'elec_bus_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 123, "sam_field_name": 'ELEC BUS POC COUNTRY CODE', "db_column_name": 'elec_bus_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 124, "sam_field_name": 'ELEC BUS POC STATE OR PROVINCE', "db_column_name": 'elec_bus_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"position": 125, "sam_field_name": 'ELEC BUS POC U.S. PHONE', "db_column_name": 'elec_bus_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 126, "sam_field_name": 'ELEC BUS POC U.S. PHONE EXT', "db_column_name": 'elec_bus_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 127, "sam_field_name": 'ELEC BUS POC NON-U.S. PHONE', "db_column_name": 'elec_bus_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 128, "sam_field_name": 'ELEC BUS POC FAX U.S. ONLY', "db_column_name": 'elec_bus_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 129, "sam_field_name": 'ELEC BUS POC EMAIL', "db_column_name": 'elec_bus_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 130, "sam_field_name": 'ALT ELEC POC BUS POC FIRST NAME', "db_column_name": 'alt_elec_poc_bus_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 131, "sam_field_name": 'ALT ELEC POC BUS POC MIDDLE INITIAL', "db_column_name": 'alt_elec_poc_bus_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 132, "sam_field_name": 'ALT ELEC POC BUS POC LAST NAME', "db_column_name": 'alt_elec_poc_bus_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'Public'},
    {"position": 133, "sam_field_name": 'ALT ELEC POC BUS POC TITLE', "db_column_name": 'alt_elec_poc_bus_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 134, "sam_field_name": 'ALT ELEC POC BUS ST ADD 1', "db_column_name": 'alt_elec_poc_bus_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 135, "sam_field_name": 'ALT ELEC POC BUS ST ADD 2', "db_column_name": 'alt_elec_poc_bus_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Public'},
    {"position": 136, "sam_field_name": 'ALT ELEC POC BUS CITY', "db_column_name": 'alt_elec_poc_bus_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Public'},
    {"position": 137, "sam_field_name": 'ALT ELEC POC BUS ZIP/POSTAL CODE', "db_column_name": 'alt_elec_poc_bus_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Public'},
    {"position": 138, "sam_field_name": 'ALT ELEC POC BUS ZIP CODE +4', "db_column_name": 'alt_elec_poc_bus_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 139, "sam_field_name": 'ALT ELEC POC BUS COUNTRY CODE', "db_column_name": 'alt_elec_poc_bus_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 140, "sam_field_name": 'ALT ELEC POC BUS STATE OR PROVINCE', "db_column_name": 'alt_elec_poc_bus_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Public'},
    {"position": 141, "sam_field_name": 'ALT ELEC POC BUS U.S. PHONE', "db_column_name": 'alt_elec_poc_bus_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 142, "sam_field_name": 'ALT ELEC POC BUS U.S. PHONE EXT', "db_column_name": 'alt_elec_poc_bus_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 143, "sam_field_name": 'ALT ELEC POC BUS NON-U.S. PHONE', "db_column_name": 'alt_elec_poc_bus_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 144, "sam_field_name": 'ALT ELEC POC BUS FAX U.S. ONLY', "db_column_name": 'alt_elec_poc_bus_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 145, "sam_field_name": 'ALT ELEC POC BUS EMAIL', "db_column_name": 'alt_elec_poc_bus_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 146, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC FIRST NAME', "db_column_name": 'party_performing_certification_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 147, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC MIDDLE INITIAL', "db_column_name": 'party_performing_certification_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 148, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC LAST NAME', "db_column_name": 'party_performing_certification_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 149, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC TITLE', "db_column_name": 'party_performing_certification_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 150, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC BUS ST ADD 1', "db_column_name": 'party_performing_certification_poc_bus_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 151, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC BUS ST ADD 2', "db_column_name": 'party_performing_certification_poc_bus_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 152, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC BUS CITY', "db_column_name": 'party_performing_certification_poc_bus_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 153, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC BUS ZIP/POSTAL CODE', "db_column_name": 'party_performing_certification_poc_bus_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 154, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC BUS ZIP CODE +4', "db_column_name": 'party_performing_certification_poc_bus_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 155, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC BUS COUNTRY CODE', "db_column_name": 'party_performing_certification_poc_bus_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 156, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC BUS STATE OR PROVINCE', "db_column_name": 'party_performing_certification_poc_bus_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 157, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC U.S. PHONE', "db_column_name": 'party_performing_certification_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 158, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC U.S. PHONE EXT', "db_column_name": 'party_performing_certification_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 159, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC NON-U.S. PHONE', "db_column_name": 'party_performing_certification_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 160, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC FAX U.S. ONLY', "db_column_name": 'party_performing_certification_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 161, "sam_field_name": 'PARTY PERFORMING CERTIFICATION POC EMAIL', "db_column_name": 'party_performing_certification_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 162, "sam_field_name": 'SOLE PROPRIETORSHIP POC FIRST NAME', "db_column_name": 'sole_proprietorship_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 163, "sam_field_name": 'SOLE PROPRIETORSHIP POC MIDDLE INITIAL', "db_column_name": 'sole_proprietorship_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 164, "sam_field_name": 'SOLE PROPRIETORSHIP POC LAST NAME', "db_column_name": 'sole_proprietorship_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 165, "sam_field_name": 'SOLE PROPRIETORSHIP POC TITLE', "db_column_name": 'sole_proprietorship_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 166, "sam_field_name": 'SOLE PROPRIETORSHIP POC U.S. PHONE', "db_column_name": 'sole_proprietorship_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 167, "sam_field_name": 'SOLE PROPRIETORSHIP POC U.S. PHONE EXT', "db_column_name": 'sole_proprietorship_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 168, "sam_field_name": 'SOLE PROPRIETORSHIP POC NON-U.S. PHONE', "db_column_name": 'sole_proprietorship_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 169, "sam_field_name": 'SOLE PROPRIETORSHIP POC FAX U.S. ONLY', "db_column_name": 'sole_proprietorship_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 170, "sam_field_name": 'SOLE PROPRIETORSHIP POC EMAIL', "db_column_name": 'sole_proprietorship_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 171, "sam_field_name": 'IMMEDIATE PARENT LEGAL BUSINESS NAME', "db_column_name": 'immediate_parent_legal_business_name', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 172, "sam_field_name": 'IMMEDIATE PARENT UNIQUE ENTITY ID', "db_column_name": 'immediate_parent_unique_entity_id', "datatype": 'STRING', "max_length": 12, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 173, "sam_field_name": 'IMMEDIATE PARENT ST ADD 1', "db_column_name": 'immediate_parent_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 174, "sam_field_name": 'IMMEDIATE PARENT ST ADD 2', "db_column_name": 'immediate_parent_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 175, "sam_field_name": 'IMMEDIATE PARENT CITY', "db_column_name": 'immediate_parent_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 176, "sam_field_name": 'IMMEDIATE PARENT POSTAL CODE', "db_column_name": 'immediate_parent_postal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 177, "sam_field_name": 'IMMEDIATE PARENT COUNTRY CODE', "db_column_name": 'immediate_parent_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 178, "sam_field_name": 'IMMEDIATE PARENT STATE OR PROVINCE', "db_column_name": 'immediate_parent_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 179, "sam_field_name": 'IMMEDIATE PARENT PHONE', "db_column_name": 'immediate_parent_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 180, "sam_field_name": 'HQ PARENT LEGAL BUSINESS NAME', "db_column_name": 'hq_parent_legal_business_name', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 181, "sam_field_name": 'HQ PARENT UNIQUE ENTITY ID', "db_column_name": 'hq_parent_unique_entity_id', "datatype": 'STRING', "max_length": 12, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 182, "sam_field_name": 'BLANK (DEPRECATED)', "db_column_name": 'col_182_deprecated', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 183, "sam_field_name": 'HQ PARENT ST ADD 1', "db_column_name": 'hq_parent_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 184, "sam_field_name": 'HQ PARENT ST ADD 2', "db_column_name": 'hq_parent_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 185, "sam_field_name": 'HQ PARENT CITY', "db_column_name": 'hq_parent_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 186, "sam_field_name": 'HQ PARENT POSTAL CODE', "db_column_name": 'hq_parent_postal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 187, "sam_field_name": 'HQ PARENT COUNTRY CODE', "db_column_name": 'hq_parent_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 188, "sam_field_name": 'HQ PARENT STATE OR PROVINCE', "db_column_name": 'hq_parent_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 189, "sam_field_name": 'HQ PARENT PHONE', "db_column_name": 'hq_parent_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 190, "sam_field_name": 'DOMESTIC PARENT LEGAL BUSINESS NAME', "db_column_name": 'domestic_parent_legal_business_name', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 191, "sam_field_name": 'DOMESTIC PARENT UNIQUE ENTITY ID', "db_column_name": 'domestic_parent_unique_entity_id', "datatype": 'STRING', "max_length": 12, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 192, "sam_field_name": 'BLANK (DEPRECATED)', "db_column_name": 'col_192_deprecated', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 193, "sam_field_name": 'DOMESTIC PARENT ST ADD 1', "db_column_name": 'domestic_parent_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 194, "sam_field_name": 'DOMESTIC PARENT ST ADD 2', "db_column_name": 'domestic_parent_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 195, "sam_field_name": 'DOMESTIC PARENT CITY', "db_column_name": 'domestic_parent_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 196, "sam_field_name": 'DOMESTIC PARENT POSTAL CODE', "db_column_name": 'domestic_parent_postal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 197, "sam_field_name": 'DOMESTIC PARENT COUNTRY CODE', "db_column_name": 'domestic_parent_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 198, "sam_field_name": 'DOMESTIC PARENT STATE OR PROVINCE', "db_column_name": 'domestic_parent_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 199, "sam_field_name": 'DOMESTIC PARENT PHONE', "db_column_name": 'domestic_parent_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 200, "sam_field_name": 'ULTIMATE PARENT LEGAL BUSINESS NAME', "db_column_name": 'ultimate_parent_legal_business_name', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 201, "sam_field_name": 'ULTIMATE PARENT UNIQUE ENTITY ID', "db_column_name": 'ultimate_parent_unique_entity_id', "datatype": 'STRING', "max_length": 12, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 202, "sam_field_name": 'BLANK (DEPRECATED)', "db_column_name": 'col_202_deprecated', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 203, "sam_field_name": 'ULTIMATE PARENT ST ADD 1', "db_column_name": 'ultimate_parent_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 204, "sam_field_name": 'ULTIMATE PARENT ST ADD 2', "db_column_name": 'ultimate_parent_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 205, "sam_field_name": 'ULTIMATE PARENT CITY', "db_column_name": 'ultimate_parent_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 206, "sam_field_name": 'ULTIMATE PARENT POSTAL CODE', "db_column_name": 'ultimate_parent_postal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 207, "sam_field_name": 'ULTIMATE PARENT COUNTRY CODE', "db_column_name": 'ultimate_parent_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 208, "sam_field_name": 'ULTIMATE PARENT STATE OR PROVINCE', "db_column_name": 'ultimate_parent_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 209, "sam_field_name": 'ULTIMATE PARENT PHONE', "db_column_name": 'ultimate_parent_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 210, "sam_field_name": 'EVS OUT OF BUSINESS INDICATOR', "db_column_name": 'evs_out_of_business_indicator', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 211, "sam_field_name": 'EVS MONITORING LAST UPDATED', "db_column_name": 'evs_monitoring_last_updated', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 212, "sam_field_name": 'EVS MONITORING STATUS', "db_column_name": 'evs_monitoring_status', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 213, "sam_field_name": 'EVS MONITORING LEGAL BUSINESS NAME', "db_column_name": 'evs_monitoring_legal_business_name', "datatype": 'STRING', "max_length": 120, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 214, "sam_field_name": 'EVS MONITORING DBA', "db_column_name": 'evs_monitoring_dba', "datatype": 'STRING', "max_length": 120, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 215, "sam_field_name": 'EVS MONITORING ADDRESS 1', "db_column_name": 'evs_monitoring_address_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 216, "sam_field_name": 'EVS MONITORING ADDRESS 2', "db_column_name": 'evs_monitoring_address_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 217, "sam_field_name": 'EVS MONITORING CITY', "db_column_name": 'evs_monitoring_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 218, "sam_field_name": 'EVS MONITORING POSTAL CODE', "db_column_name": 'evs_monitoring_postal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 219, "sam_field_name": 'EVS MONITORING COUNTRY CODE', "db_column_name": 'evs_monitoring_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 220, "sam_field_name": 'EVS MONITORING STATE OR PROVINCE', "db_column_name": 'evs_monitoring_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 221, "sam_field_name": 'EDI (Y/N)', "db_column_name": 'edi', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 222, "sam_field_name": 'EDI VAN PROVIDER', "db_column_name": 'edi_van_provider', "datatype": 'STRING', "max_length": 20, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 223, "sam_field_name": 'ISA QUALIFIER', "db_column_name": 'isa_qualifier', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 224, "sam_field_name": 'ISA IDENTIFIER', "db_column_name": 'isa_identifier', "datatype": 'STRING', "max_length": 15, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 225, "sam_field_name": 'FUNCTIONAL GROUP IDENTIFIER', "db_column_name": 'functional_group_identifier', "datatype": 'STRING', "max_length": 15, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 226, "sam_field_name": '820S REQUEST FLAG', "db_column_name": 'field_820s_request_flag', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 227, "sam_field_name": 'EDI POC FIRST NAME', "db_column_name": 'edi_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 228, "sam_field_name": 'EDI POC MIDDLE INITIAL', "db_column_name": 'edi_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 229, "sam_field_name": 'EDI POC LAST NAME', "db_column_name": 'edi_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 230, "sam_field_name": 'EDI POC TITLE', "db_column_name": 'edi_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 231, "sam_field_name": 'EDI POC U.S. PHONE', "db_column_name": 'edi_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 232, "sam_field_name": 'EDI POC U.S. PHONE EXT', "db_column_name": 'edi_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 233, "sam_field_name": 'EDI POC NON-U.S. PHONE', "db_column_name": 'edi_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 234, "sam_field_name": 'EDI POC FAX U.S. ONLY', "db_column_name": 'edi_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 235, "sam_field_name": 'EDI POC EMAIL', "db_column_name": 'edi_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 236, "sam_field_name": 'TAX IDENTIFIER TYPE', "db_column_name": 'tax_identifier_type', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 237, "sam_field_name": 'TAX IDENTIFIER NUMBER', "db_column_name": 'tax_identifier_number', "datatype": 'STRING', "max_length": 9, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 238, "sam_field_name": 'AVERAGE NUMBER OF EMPLOYEES', "db_column_name": 'average_number_of_employees', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 239, "sam_field_name": 'AVERAGE ANNUAL REVENUE', "db_column_name": 'average_annual_revenue', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 240, "sam_field_name": 'FINANCIAL INSTITUTE', "db_column_name": 'financial_institute', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 241, "sam_field_name": 'ACCOUNT NUMBER', "db_column_name": 'account_number', "datatype": 'STRING', "max_length": 20, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 242, "sam_field_name": 'ABA ROUTING ID', "db_column_name": 'aba_routing_id', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 243, "sam_field_name": 'ACCOUNT TYPE', "db_column_name": 'account_type', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 244, "sam_field_name": 'LOCKBOX NUMBER', "db_column_name": 'lockbox_number', "datatype": 'STRING', "max_length": 20, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 245, "sam_field_name": 'AUTHORIZATION DATE', "db_column_name": 'authorization_date', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 246, "sam_field_name": 'EFT WAIVER', "db_column_name": 'eft_waiver', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 247, "sam_field_name": 'ACH U.S. PHONE', "db_column_name": 'ach_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 248, "sam_field_name": 'ACH NON-U.S. PHONE', "db_column_name": 'ach_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 249, "sam_field_name": 'ACH FAX', "db_column_name": 'ach_fax', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 250, "sam_field_name": 'ACH EMAIL', "db_column_name": 'ach_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 251, "sam_field_name": 'REMITTANCE NAME', "db_column_name": 'remittance_name', "datatype": 'STRING', "max_length": 120, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 252, "sam_field_name": 'REMITTANCE ADDRESS LINE 1', "db_column_name": 'remittance_address_line_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 253, "sam_field_name": 'REMITTANCE ADDRESS LINE 2', "db_column_name": 'remittance_address_line_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 254, "sam_field_name": 'REMITTANCE CITY', "db_column_name": 'remittance_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 255, "sam_field_name": 'REMITTANCE STATE OR PROVINCE', "db_column_name": 'remittance_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 256, "sam_field_name": 'REMITTANCE ZIP/POSTAL CODE', "db_column_name": 'remittance_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 257, "sam_field_name": 'REMITTANCE ZIP CODE +4', "db_column_name": 'remittance_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 258, "sam_field_name": 'REMITTANCE COUNTRY', "db_column_name": 'remittance_country', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 259, "sam_field_name": 'ACCOUNTS RECEIVABLE POC FIRST NAME', "db_column_name": 'accounts_receivable_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 260, "sam_field_name": 'ACCOUNTS RECEIVABLE POC MIDDLE INITIAL', "db_column_name": 'accounts_receivable_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 261, "sam_field_name": 'ACCOUNTS RECEIVABLE POC LAST NAME', "db_column_name": 'accounts_receivable_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 262, "sam_field_name": 'ACCOUNTS RECEIVABLE POC TITLE', "db_column_name": 'accounts_receivable_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 263, "sam_field_name": 'ACCOUNTS RECEIVABLE POC U.S. PHONE', "db_column_name": 'accounts_receivable_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 264, "sam_field_name": 'ACCOUNTS RECEIVABLE POC U.S. PHONE EXT', "db_column_name": 'accounts_receivable_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 265, "sam_field_name": 'ACCOUNTS RECEIVABLE POC NON-U.S. PHONE', "db_column_name": 'accounts_receivable_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 266, "sam_field_name": 'ACCOUNTS RECEIVABLE POC FAX U.S. ONLY', "db_column_name": 'accounts_receivable_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 267, "sam_field_name": 'ACCOUNTS RECEIVABLE POC EMAIL', "db_column_name": 'accounts_receivable_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 268, "sam_field_name": 'ACCOUNTS PAYABLE POC FIRST NAME', "db_column_name": 'accounts_payable_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 269, "sam_field_name": 'ACCOUNTS PAYABLE POC MIDDLE INITIAL', "db_column_name": 'accounts_payable_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 270, "sam_field_name": 'ACCOUNTS PAYABLE POC LAST NAME', "db_column_name": 'accounts_payable_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 271, "sam_field_name": 'ACCOUNTS PAYABLE POC TITLE', "db_column_name": 'accounts_payable_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 272, "sam_field_name": 'ACCOUNTS PAYABLE POC ST ADD 1', "db_column_name": 'accounts_payable_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 273, "sam_field_name": 'ACCOUNTS PAYABLE POC ST ADD 2', "db_column_name": 'accounts_payable_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 274, "sam_field_name": 'ACCOUNTS PAYABLE POC CITY', "db_column_name": 'accounts_payable_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 275, "sam_field_name": 'ACCOUNTS PAYABLE POC ZIP/POSTAL CODE', "db_column_name": 'accounts_payable_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 276, "sam_field_name": 'ACCOUNTS PAYABLE POC ZIP CODE +4', "db_column_name": 'accounts_payable_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 277, "sam_field_name": 'ACCOUNTS PAYABLE POC COUNTRY CODE', "db_column_name": 'accounts_payable_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 278, "sam_field_name": 'ACCOUNTS PAYABLE POC STATE OR PROVINCE', "db_column_name": 'accounts_payable_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 279, "sam_field_name": 'ACCOUNTS PAYABLE POC U.S. PHONE', "db_column_name": 'accounts_payable_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 280, "sam_field_name": 'ACCOUNTS PAYABLE POC U.S. PHONE EXT', "db_column_name": 'accounts_payable_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 281, "sam_field_name": 'ACCOUNTS PAYABLE POC NON-U.S. PHONE', "db_column_name": 'accounts_payable_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 282, "sam_field_name": 'ACCOUNTS PAYABLE POC FAX U.S. ONLY', "db_column_name": 'accounts_payable_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 283, "sam_field_name": 'ACCOUNTS PAYABLE POC EMAIL', "db_column_name": 'accounts_payable_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 284, "sam_field_name": 'MPIN', "db_column_name": 'mpin', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 285, "sam_field_name": 'NAICS EXCEPTION COUNTER', "db_column_name": 'naics_exception_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 286, "sam_field_name": 'NAICS EXCEPTION STRING', "db_column_name": 'naics_exception_string', "datatype": 'STRING', "max_length": 1100, "sensitivity_level": 'Public'},
    {"position": 287, "sam_field_name": 'DEBT SUBJECT TO OFFSET FLAG', "db_column_name": 'debt_subject_to_offset_flag', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"position": 288, "sam_field_name": 'EXCLUSION STATUS FLAG', "db_column_name": 'exclusion_status_flag', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"position": 289, "sam_field_name": 'SBA BUSINESS TYPES COUNTER', "db_column_name": 'sba_business_types_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 290, "sam_field_name": 'SBA BUSINESS TYPES STRING', "db_column_name": 'sba_business_types_string', "datatype": 'STRING', "max_length": 125, "sensitivity_level": 'Public'},
    {"position": 291, "sam_field_name": 'SAM NUMERICS COUNTER', "db_column_name": 'sam_numerics_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 292, "sam_field_name": 'SAM NUMERICS CODE STRING', "db_column_name": 'sam_numerics_code_string', "datatype": 'STRING', "max_length": 1600, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 293, "sam_field_name": 'NO PUBLIC DISPLAY FLAG', "db_column_name": 'no_public_display_flag', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 294, "sam_field_name": 'DISASTER RESPONSE COUNTER', "db_column_name": 'disaster_response_counter', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 295, "sam_field_name": 'DISASTER RESPONSE STRING', "db_column_name": 'disaster_response_string', "datatype": 'STRING', "max_length": 75, "sensitivity_level": 'Public'},
    {"position": 296, "sam_field_name": 'ANNUAL IGT REVENUE', "db_column_name": 'annual_igt_revenue', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 297, "sam_field_name": 'AGENCY LOCATION CODE', "db_column_name": 'agency_location_code', "datatype": 'STRING', "max_length": 8, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 298, "sam_field_name": 'DISBURSING OFFICE SYMBOL', "db_column_name": 'disbursing_office_symbol', "datatype": 'STRING', "max_length": 5, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 299, "sam_field_name": 'MERCHANT ID 1', "db_column_name": 'merchant_id_1', "datatype": 'STRING', "max_length": 130, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 300, "sam_field_name": 'MERCHANT ID 2', "db_column_name": 'merchant_id_2', "datatype": 'STRING', "max_length": 130, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 301, "sam_field_name": 'ACCOUNTING STATION', "db_column_name": 'accounting_station', "datatype": 'STRING', "max_length": 6, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 302, "sam_field_name": 'SOURCE', "db_column_name": 'source', "datatype": 'STRING', "max_length": 7, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 303, "sam_field_name": 'DEPARTMENT CODE', "db_column_name": 'department_code', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 304, "sam_field_name": 'HIERARCHY DEPARTMENT CODE', "db_column_name": 'hierarchy_department_code', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 305, "sam_field_name": 'HIERARCHY DEPARTMENT NAME', "db_column_name": 'hierarchy_department_name', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 306, "sam_field_name": 'HIERARCHY AGENCY CODE', "db_column_name": 'hierarchy_agency_code', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 307, "sam_field_name": 'HIERARCHY AGENCY NAME', "db_column_name": 'hierarchy_agency_name', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 308, "sam_field_name": 'HIERARCHY OFFICE CODE', "db_column_name": 'hierarchy_office_code', "datatype": 'STRING', "max_length": 6, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 309, "sam_field_name": 'ELIMINATIONS POC FIRST NAME', "db_column_name": 'eliminations_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 310, "sam_field_name": 'ELIMINATIONS POC MIDDLE INITIAL', "db_column_name": 'eliminations_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 311, "sam_field_name": 'ELIMINATIONS POC LAST NAME', "db_column_name": 'eliminations_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 312, "sam_field_name": 'ELIMINATIONS POC TITLE', "db_column_name": 'eliminations_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 313, "sam_field_name": 'ELIMINATIONS POC ST ADD 1', "db_column_name": 'eliminations_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 314, "sam_field_name": 'ELIMINATIONS POC ST ADD 2', "db_column_name": 'eliminations_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 315, "sam_field_name": 'ELIMINATIONS POC CITY', "db_column_name": 'eliminations_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 316, "sam_field_name": 'ELIMINATIONS POC ZIP/POSTAL CODE', "db_column_name": 'eliminations_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 317, "sam_field_name": 'ELIMINATIONS POC ZIP CODE +4', "db_column_name": 'eliminations_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 318, "sam_field_name": 'ELIMINATIONS POC COUNTRY CODE', "db_column_name": 'eliminations_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 319, "sam_field_name": 'ELIMINATIONS POC STATE OR PROVINCE', "db_column_name": 'eliminations_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 320, "sam_field_name": 'ELIMINATIONS POC U.S. PHONE', "db_column_name": 'eliminations_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 321, "sam_field_name": 'ELIMINATIONS POC U.S. PHONE EXT', "db_column_name": 'eliminations_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 322, "sam_field_name": 'ELIMINATIONS POC NON-U.S. PHONE', "db_column_name": 'eliminations_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 323, "sam_field_name": 'ELIMINATIONS POC FAX U.S. ONLY', "db_column_name": 'eliminations_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 324, "sam_field_name": 'ELIMINATIONS POC EMAIL', "db_column_name": 'eliminations_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 325, "sam_field_name": 'SALES POC FIRST NAME', "db_column_name": 'sales_poc_first_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 326, "sam_field_name": 'SALES POC MIDDLE INITIAL', "db_column_name": 'sales_poc_middle_initial', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 327, "sam_field_name": 'SALES POC LAST NAME', "db_column_name": 'sales_poc_last_name', "datatype": 'STRING', "max_length": 65, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 328, "sam_field_name": 'SALES POC TITLE', "db_column_name": 'sales_poc_title', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 329, "sam_field_name": 'SALES POC ST ADD 1', "db_column_name": 'sales_poc_st_add_1', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 330, "sam_field_name": 'SALES POC ST ADD 2', "db_column_name": 'sales_poc_st_add_2', "datatype": 'STRING', "max_length": 150, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 331, "sam_field_name": 'SALES POC CITY', "db_column_name": 'sales_poc_city', "datatype": 'STRING', "max_length": 40, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 332, "sam_field_name": 'SALES POC ZIP/POSTAL CODE', "db_column_name": 'sales_poc_zippostal_code', "datatype": 'STRING', "max_length": 50, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 333, "sam_field_name": 'SALES POC ZIP CODE +4', "db_column_name": 'sales_poc_zip_code_4', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 334, "sam_field_name": 'SALES POC COUNTRY CODE', "db_column_name": 'sales_poc_country_code', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 335, "sam_field_name": 'SALES POC STATE OR PROVINCE', "db_column_name": 'sales_poc_state_or_province', "datatype": 'STRING', "max_length": 55, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 336, "sam_field_name": 'SALES POC U.S. PHONE', "db_column_name": 'sales_poc_us_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 337, "sam_field_name": 'SALES POC U.S. PHONE EXT', "db_column_name": 'sales_poc_us_phone_ext', "datatype": 'STRING', "max_length": 25, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 338, "sam_field_name": 'SALES POC NON-U.S. PHONE', "db_column_name": 'sales_poc_nonus_phone', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 339, "sam_field_name": 'SALES POC FAX U.S. ONLY', "db_column_name": 'sales_poc_fax_us_only', "datatype": 'STRING', "max_length": 30, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 340, "sam_field_name": 'SALES POC EMAIL', "db_column_name": 'sales_poc_email', "datatype": 'STRING', "max_length": 80, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 341, "sam_field_name": 'TAXPAYER NAME', "db_column_name": 'taxpayer_name', "datatype": 'STRING', "max_length": 120, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 342, "sam_field_name": 'ENTITY EVS SOURCE', "db_column_name": 'entity_evs_source', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'Public'},
    {"position": 343, "sam_field_name": 'HQ PARENT EVS SOURCE', "db_column_name": 'hq_parent_evs_source', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 344, "sam_field_name": 'DOMESTIC PARENT EVS SOURCE', "db_column_name": 'domestic_parent_evs_source', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 345, "sam_field_name": 'ULTIMATE PARENT EVS SOURCE', "db_column_name": 'ultimate_parent_evs_source', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 346, "sam_field_name": 'IMMEDIATE PARENT EVS SOURCE', "db_column_name": 'immediate_parent_evs_source', "datatype": 'STRING', "max_length": 10, "sensitivity_level": 'FOUO (CUI)'},
    {"position": 347, "sam_field_name": 'TIN TYPE', "db_column_name": 'tin_type', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 348, "sam_field_name": 'TIN NUMBER', "db_column_name": 'tin_number', "datatype": 'STRING', "max_length": 9, "sensitivity_level": 'Sensitive (CUI)'},
    {"position": 349, "sam_field_name": 'FLEX FIELD 6', "db_column_name": 'flex_field_06', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 350, "sam_field_name": 'FLEX FIELD 7', "db_column_name": 'flex_field_07', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 351, "sam_field_name": 'FLEX FIELD 8', "db_column_name": 'flex_field_08', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 352, "sam_field_name": 'FLEX FIELD 9', "db_column_name": 'flex_field_09', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 353, "sam_field_name": 'FLEX FIELD 10', "db_column_name": 'flex_field_10', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 354, "sam_field_name": 'FLEX FIELD 11', "db_column_name": 'flex_field_11', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 355, "sam_field_name": 'FLEX FIELD 12', "db_column_name": 'flex_field_12', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 356, "sam_field_name": 'FLEX FIELD 13', "db_column_name": 'flex_field_13', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 357, "sam_field_name": 'FLEX FIELD 14', "db_column_name": 'flex_field_14', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 358, "sam_field_name": 'FLEX FIELD 15', "db_column_name": 'flex_field_15', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 359, "sam_field_name": 'FLEX FIELD 16', "db_column_name": 'flex_field_16', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 360, "sam_field_name": 'FLEX FIELD 17', "db_column_name": 'flex_field_17', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 361, "sam_field_name": 'FLEX FIELD 18', "db_column_name": 'flex_field_18', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 362, "sam_field_name": 'FLEX FIELD 19', "db_column_name": 'flex_field_19', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 363, "sam_field_name": 'FLEX FIELD 20', "db_column_name": 'flex_field_20', "datatype": 'STRING', "max_length": None, "sensitivity_level": 'Public'},
    {"position": 364, "sam_field_name": 'FLEX FIELD 21', "db_column_name": 'flex_field_21', "datatype": 'STRING', "max_length": 1, "sensitivity_level": 'Public'},
    {"position": 365, "sam_field_name": 'FLEX FIELD 22', "db_column_name": 'flex_field_22', "datatype": 'STRING', "max_length": 2, "sensitivity_level": 'Public'},
    {"position": 366, "sam_field_name": 'FLEX FIELD 23', "db_column_name": 'flex_field_23', "datatype": 'STRING', "max_length": 3, "sensitivity_level": 'Public'},
    {"position": 367, "sam_field_name": 'FLEX FIELD 24', "db_column_name": 'flex_field_24', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
    {"position": 368, "sam_field_name": 'END OF RECORD INDICATOR', "db_column_name": 'end_of_record_indicator', "datatype": 'STRING', "max_length": 4, "sensitivity_level": 'Public'},
]


SAM_GOV_DB_COLUMN_NAMES: list[str] = [col["db_column_name"] for col in SAM_GOV_COLUMNS]


SAM_GOV_COLUMN_COUNT: int = len(SAM_GOV_COLUMNS)


if __name__ == "__main__":
    print(f"SAM.gov column count: {SAM_GOV_COLUMN_COUNT}")
    assert SAM_GOV_COLUMN_COUNT == 368, f"Expected 368 columns, got {SAM_GOV_COLUMN_COUNT}"
    print(f"First column: {SAM_GOV_COLUMNS[0]}")
    print(f"Last column:  {SAM_GOV_COLUMNS[-1]}")
    print("All assertions passed.")
