# app/services/usaspending_column_map.py — USASpending.gov bulk download column mapping
#
# Generated from FY2026_All_Contracts_Full CSV header row (297 columns).
# Delta files have 2 additional prepended columns (correction_delete_ind, agency_id).
# Do not edit manually — regenerate from the CSV header if schema changes.

from __future__ import annotations


USASPENDING_COLUMNS: list[dict] = [
    {"position": 1, "csv_header_name": "contract_transaction_unique_key", "db_column_name": "contract_transaction_unique_key", "description": "Unique key per transaction row"},
    {"position": 2, "csv_header_name": "contract_award_unique_key", "db_column_name": "contract_award_unique_key", "description": "Unique key per award"},
    {"position": 3, "csv_header_name": "award_id_piid", "db_column_name": "award_id_piid", "description": "Procurement Instrument Identifier (PIID)"},
    {"position": 4, "csv_header_name": "modification_number", "db_column_name": "modification_number", "description": "Modification number of the transaction"},
    {"position": 5, "csv_header_name": "transaction_number", "db_column_name": "transaction_number", "description": "Transaction number within the award"},
    {"position": 6, "csv_header_name": "parent_award_agency_id", "db_column_name": "parent_award_agency_id", "description": "Agency ID of the parent award"},
    {"position": 7, "csv_header_name": "parent_award_agency_name", "db_column_name": "parent_award_agency_name", "description": "Agency name of the parent award"},
    {"position": 8, "csv_header_name": "parent_award_id_piid", "db_column_name": "parent_award_id_piid", "description": "PIID of the parent award (IDV)"},
    {"position": 9, "csv_header_name": "parent_award_modification_number", "db_column_name": "parent_award_modification_number", "description": "Modification number of the parent award"},
    {"position": 10, "csv_header_name": "federal_action_obligation", "db_column_name": "federal_action_obligation", "description": "Dollar amount obligated by this transaction"},
    {"position": 11, "csv_header_name": "total_dollars_obligated", "db_column_name": "total_dollars_obligated", "description": "Total dollars obligated on the award"},
    {"position": 12, "csv_header_name": "total_outlayed_amount_for_overall_award", "db_column_name": "total_outlayed_amount_for_overall_award", "description": "Total outlayed amount for the overall award"},
    {"position": 13, "csv_header_name": "base_and_exercised_options_value", "db_column_name": "base_and_exercised_options_value", "description": "Base and exercised options value"},
    {"position": 14, "csv_header_name": "current_total_value_of_award", "db_column_name": "current_total_value_of_award", "description": "Current total value of the award"},
    {"position": 15, "csv_header_name": "base_and_all_options_value", "db_column_name": "base_and_all_options_value", "description": "Base and all options value (potential ceiling)"},
    {"position": 16, "csv_header_name": "potential_total_value_of_award", "db_column_name": "potential_total_value_of_award", "description": "Potential total value of the award"},
    {"position": 17, "csv_header_name": "disaster_emergency_fund_codes_for_overall_award", "db_column_name": "disaster_emergency_fund_codes_for_overall_award", "description": "DEFC codes for the overall award"},
    {"position": 18, "csv_header_name": "outlayed_amount_from_COVID-19_supplementals_for_overall_award", "db_column_name": "outlayed_amount_from_covid_19_supplementals_for_overall_award", "description": "Outlayed amount from COVID-19 supplementals (CSV header: outlayed_amount_from_COVID-19_supplementals_for_overall_award)"},
    {"position": 19, "csv_header_name": "obligated_amount_from_COVID-19_supplementals_for_overall_award", "db_column_name": "obligated_amount_from_covid_19_supplementals_for_overall_award", "description": "Obligated amount from COVID-19 supplementals (CSV header: obligated_amount_from_COVID-19_supplementals_for_overall_award)"},
    {"position": 20, "csv_header_name": "outlayed_amount_from_IIJA_supplemental_for_overall_award", "db_column_name": "outlayed_amount_from_iija_supplemental_for_overall_award", "description": "Outlayed amount from IIJA supplemental (CSV header: outlayed_amount_from_IIJA_supplemental_for_overall_award)"},
    {"position": 21, "csv_header_name": "obligated_amount_from_IIJA_supplemental_for_overall_award", "db_column_name": "obligated_amount_from_iija_supplemental_for_overall_award", "description": "Obligated amount from IIJA supplemental (CSV header: obligated_amount_from_IIJA_supplemental_for_overall_award)"},
    {"position": 22, "csv_header_name": "action_date", "db_column_name": "action_date", "description": "Date the action was signed"},
    {"position": 23, "csv_header_name": "action_date_fiscal_year", "db_column_name": "action_date_fiscal_year", "description": "Fiscal year of the action date"},
    {"position": 24, "csv_header_name": "period_of_performance_start_date", "db_column_name": "period_of_performance_start_date", "description": "Start date of the period of performance"},
    {"position": 25, "csv_header_name": "period_of_performance_current_end_date", "db_column_name": "period_of_performance_current_end_date", "description": "Current end date of the period of performance"},
    {"position": 26, "csv_header_name": "period_of_performance_potential_end_date", "db_column_name": "period_of_performance_potential_end_date", "description": "Potential end date including all options"},
    {"position": 27, "csv_header_name": "ordering_period_end_date", "db_column_name": "ordering_period_end_date", "description": "End date of the ordering period"},
    {"position": 28, "csv_header_name": "solicitation_date", "db_column_name": "solicitation_date", "description": "Date the solicitation was issued"},
    {"position": 29, "csv_header_name": "awarding_agency_code", "db_column_name": "awarding_agency_code", "description": "Code of the awarding agency"},
    {"position": 30, "csv_header_name": "awarding_agency_name", "db_column_name": "awarding_agency_name", "description": "Name of the awarding agency"},
    {"position": 31, "csv_header_name": "awarding_sub_agency_code", "db_column_name": "awarding_sub_agency_code", "description": "Code of the awarding sub-agency"},
    {"position": 32, "csv_header_name": "awarding_sub_agency_name", "db_column_name": "awarding_sub_agency_name", "description": "Name of the awarding sub-agency"},
    {"position": 33, "csv_header_name": "awarding_office_code", "db_column_name": "awarding_office_code", "description": "Code of the awarding office"},
    {"position": 34, "csv_header_name": "awarding_office_name", "db_column_name": "awarding_office_name", "description": "Name of the awarding office"},
    {"position": 35, "csv_header_name": "funding_agency_code", "db_column_name": "funding_agency_code", "description": "Code of the funding agency"},
    {"position": 36, "csv_header_name": "funding_agency_name", "db_column_name": "funding_agency_name", "description": "Name of the funding agency"},
    {"position": 37, "csv_header_name": "funding_sub_agency_code", "db_column_name": "funding_sub_agency_code", "description": "Code of the funding sub-agency"},
    {"position": 38, "csv_header_name": "funding_sub_agency_name", "db_column_name": "funding_sub_agency_name", "description": "Name of the funding sub-agency"},
    {"position": 39, "csv_header_name": "funding_office_code", "db_column_name": "funding_office_code", "description": "Code of the funding office"},
    {"position": 40, "csv_header_name": "funding_office_name", "db_column_name": "funding_office_name", "description": "Name of the funding office"},
    {"position": 41, "csv_header_name": "treasury_accounts_funding_this_award", "db_column_name": "treasury_accounts_funding_this_award", "description": "Treasury account symbols funding this award"},
    {"position": 42, "csv_header_name": "federal_accounts_funding_this_award", "db_column_name": "federal_accounts_funding_this_award", "description": "Federal accounts funding this award"},
    {"position": 43, "csv_header_name": "object_classes_funding_this_award", "db_column_name": "object_classes_funding_this_award", "description": "Object classes funding this award"},
    {"position": 44, "csv_header_name": "program_activities_funding_this_award", "db_column_name": "program_activities_funding_this_award", "description": "Program activities funding this award"},
    {"position": 45, "csv_header_name": "foreign_funding", "db_column_name": "foreign_funding", "description": "Foreign funding indicator code"},
    {"position": 46, "csv_header_name": "foreign_funding_description", "db_column_name": "foreign_funding_description", "description": "Foreign funding indicator description"},
    {"position": 47, "csv_header_name": "sam_exception", "db_column_name": "sam_exception", "description": "SAM.gov exception code"},
    {"position": 48, "csv_header_name": "sam_exception_description", "db_column_name": "sam_exception_description", "description": "SAM.gov exception description"},
    {"position": 49, "csv_header_name": "recipient_uei", "db_column_name": "recipient_uei", "description": "Recipient Unique Entity Identifier"},
    {"position": 50, "csv_header_name": "recipient_duns", "db_column_name": "recipient_duns", "description": "Recipient DUNS number (legacy)"},
    {"position": 51, "csv_header_name": "recipient_name", "db_column_name": "recipient_name", "description": "Recipient legal business name"},
    {"position": 52, "csv_header_name": "recipient_name_raw", "db_column_name": "recipient_name_raw", "description": "Recipient name as reported (raw)"},
    {"position": 53, "csv_header_name": "recipient_doing_business_as_name", "db_column_name": "recipient_doing_business_as_name", "description": "Recipient DBA name"},
    {"position": 54, "csv_header_name": "cage_code", "db_column_name": "cage_code", "description": "Commercial and Government Entity code"},
    {"position": 55, "csv_header_name": "recipient_parent_uei", "db_column_name": "recipient_parent_uei", "description": "Recipient parent UEI"},
    {"position": 56, "csv_header_name": "recipient_parent_duns", "db_column_name": "recipient_parent_duns", "description": "Recipient parent DUNS (legacy)"},
    {"position": 57, "csv_header_name": "recipient_parent_name", "db_column_name": "recipient_parent_name", "description": "Recipient parent legal business name"},
    {"position": 58, "csv_header_name": "recipient_parent_name_raw", "db_column_name": "recipient_parent_name_raw", "description": "Recipient parent name as reported (raw)"},
    {"position": 59, "csv_header_name": "recipient_country_code", "db_column_name": "recipient_country_code", "description": "Recipient country code"},
    {"position": 60, "csv_header_name": "recipient_country_name", "db_column_name": "recipient_country_name", "description": "Recipient country name"},
    {"position": 61, "csv_header_name": "recipient_address_line_1", "db_column_name": "recipient_address_line_1", "description": "Recipient address line 1"},
    {"position": 62, "csv_header_name": "recipient_address_line_2", "db_column_name": "recipient_address_line_2", "description": "Recipient address line 2"},
    {"position": 63, "csv_header_name": "recipient_city_name", "db_column_name": "recipient_city_name", "description": "Recipient city name"},
    {"position": 64, "csv_header_name": "prime_award_transaction_recipient_county_fips_code", "db_column_name": "prime_award_transaction_recipient_county_fips_code", "description": "Recipient county FIPS code"},
    {"position": 65, "csv_header_name": "recipient_county_name", "db_column_name": "recipient_county_name", "description": "Recipient county name"},
    {"position": 66, "csv_header_name": "prime_award_transaction_recipient_state_fips_code", "db_column_name": "prime_award_transaction_recipient_state_fips_code", "description": "Recipient state FIPS code"},
    {"position": 67, "csv_header_name": "recipient_state_code", "db_column_name": "recipient_state_code", "description": "Recipient state code"},
    {"position": 68, "csv_header_name": "recipient_state_name", "db_column_name": "recipient_state_name", "description": "Recipient state name"},
    {"position": 69, "csv_header_name": "recipient_zip_4_code", "db_column_name": "recipient_zip_4_code", "description": "Recipient ZIP+4 code"},
    {"position": 70, "csv_header_name": "prime_award_transaction_recipient_cd_original", "db_column_name": "prime_award_transaction_recipient_cd_original", "description": "Recipient congressional district (original)"},
    {"position": 71, "csv_header_name": "prime_award_transaction_recipient_cd_current", "db_column_name": "prime_award_transaction_recipient_cd_current", "description": "Recipient congressional district (current)"},
    {"position": 72, "csv_header_name": "recipient_phone_number", "db_column_name": "recipient_phone_number", "description": "Recipient phone number"},
    {"position": 73, "csv_header_name": "recipient_fax_number", "db_column_name": "recipient_fax_number", "description": "Recipient fax number"},
    {"position": 74, "csv_header_name": "primary_place_of_performance_country_code", "db_column_name": "primary_place_of_performance_country_code", "description": "Place of performance country code"},
    {"position": 75, "csv_header_name": "primary_place_of_performance_country_name", "db_column_name": "primary_place_of_performance_country_name", "description": "Place of performance country name"},
    {"position": 76, "csv_header_name": "primary_place_of_performance_city_name", "db_column_name": "primary_place_of_performance_city_name", "description": "Place of performance city name"},
    {"position": 77, "csv_header_name": "prime_award_transaction_place_of_performance_county_fips_code", "db_column_name": "prime_award_transaction_place_of_performance_county_fips_code", "description": "Place of performance county FIPS code"},
    {"position": 78, "csv_header_name": "primary_place_of_performance_county_name", "db_column_name": "primary_place_of_performance_county_name", "description": "Place of performance county name"},
    {"position": 79, "csv_header_name": "prime_award_transaction_place_of_performance_state_fips_code", "db_column_name": "prime_award_transaction_place_of_performance_state_fips_code", "description": "Place of performance state FIPS code"},
    {"position": 80, "csv_header_name": "primary_place_of_performance_state_code", "db_column_name": "primary_place_of_performance_state_code", "description": "Place of performance state code"},
    {"position": 81, "csv_header_name": "primary_place_of_performance_state_name", "db_column_name": "primary_place_of_performance_state_name", "description": "Place of performance state name"},
    {"position": 82, "csv_header_name": "primary_place_of_performance_zip_4", "db_column_name": "primary_place_of_performance_zip_4", "description": "Place of performance ZIP+4"},
    {"position": 83, "csv_header_name": "prime_award_transaction_place_of_performance_cd_original", "db_column_name": "prime_award_transaction_place_of_performance_cd_original", "description": "Place of performance congressional district (original)"},
    {"position": 84, "csv_header_name": "prime_award_transaction_place_of_performance_cd_current", "db_column_name": "prime_award_transaction_place_of_performance_cd_current", "description": "Place of performance congressional district (current)"},
    {"position": 85, "csv_header_name": "award_or_idv_flag", "db_column_name": "award_or_idv_flag", "description": "Flag indicating award or IDV"},
    {"position": 86, "csv_header_name": "award_type_code", "db_column_name": "award_type_code", "description": "Award type code"},
    {"position": 87, "csv_header_name": "award_type", "db_column_name": "award_type", "description": "Award type description"},
    {"position": 88, "csv_header_name": "idv_type_code", "db_column_name": "idv_type_code", "description": "IDV type code"},
    {"position": 89, "csv_header_name": "idv_type", "db_column_name": "idv_type", "description": "IDV type description"},
    {"position": 90, "csv_header_name": "multiple_or_single_award_idv_code", "db_column_name": "multiple_or_single_award_idv_code", "description": "Multiple or single award IDV code"},
    {"position": 91, "csv_header_name": "multiple_or_single_award_idv", "db_column_name": "multiple_or_single_award_idv", "description": "Multiple or single award IDV description"},
    {"position": 92, "csv_header_name": "type_of_idc_code", "db_column_name": "type_of_idc_code", "description": "Type of IDC code"},
    {"position": 93, "csv_header_name": "type_of_idc", "db_column_name": "type_of_idc", "description": "Type of IDC description"},
    {"position": 94, "csv_header_name": "type_of_contract_pricing_code", "db_column_name": "type_of_contract_pricing_code", "description": "Type of contract pricing code"},
    {"position": 95, "csv_header_name": "type_of_contract_pricing", "db_column_name": "type_of_contract_pricing", "description": "Type of contract pricing description"},
    {"position": 96, "csv_header_name": "transaction_description", "db_column_name": "transaction_description", "description": "Description of the transaction"},
    {"position": 97, "csv_header_name": "prime_award_base_transaction_description", "db_column_name": "prime_award_base_transaction_description", "description": "Base transaction description of the prime award"},
    {"position": 98, "csv_header_name": "action_type_code", "db_column_name": "action_type_code", "description": "Action type code"},
    {"position": 99, "csv_header_name": "action_type", "db_column_name": "action_type", "description": "Action type description"},
    {"position": 100, "csv_header_name": "solicitation_identifier", "db_column_name": "solicitation_identifier", "description": "Solicitation identifier"},
    {"position": 101, "csv_header_name": "number_of_actions", "db_column_name": "number_of_actions", "description": "Number of actions on the award"},
    {"position": 102, "csv_header_name": "inherently_governmental_functions", "db_column_name": "inherently_governmental_functions", "description": "Inherently governmental functions code"},
    {"position": 103, "csv_header_name": "inherently_governmental_functions_description", "db_column_name": "inherently_governmental_functions_description", "description": "Inherently governmental functions description"},
    {"position": 104, "csv_header_name": "product_or_service_code", "db_column_name": "product_or_service_code", "description": "Product or Service Code (PSC)"},
    {"position": 105, "csv_header_name": "product_or_service_code_description", "db_column_name": "product_or_service_code_description", "description": "PSC description"},
    {"position": 106, "csv_header_name": "contract_bundling_code", "db_column_name": "contract_bundling_code", "description": "Contract bundling code"},
    {"position": 107, "csv_header_name": "contract_bundling", "db_column_name": "contract_bundling", "description": "Contract bundling description"},
    {"position": 108, "csv_header_name": "dod_claimant_program_code", "db_column_name": "dod_claimant_program_code", "description": "DoD claimant program code"},
    {"position": 109, "csv_header_name": "dod_claimant_program_description", "db_column_name": "dod_claimant_program_description", "description": "DoD claimant program description"},
    {"position": 110, "csv_header_name": "naics_code", "db_column_name": "naics_code", "description": "NAICS code"},
    {"position": 111, "csv_header_name": "naics_description", "db_column_name": "naics_description", "description": "NAICS description"},
    {"position": 112, "csv_header_name": "recovered_materials_sustainability_code", "db_column_name": "recovered_materials_sustainability_code", "description": "Recovered materials/sustainability code"},
    {"position": 113, "csv_header_name": "recovered_materials_sustainability", "db_column_name": "recovered_materials_sustainability", "description": "Recovered materials/sustainability description"},
    {"position": 114, "csv_header_name": "domestic_or_foreign_entity_code", "db_column_name": "domestic_or_foreign_entity_code", "description": "Domestic or foreign entity code"},
    {"position": 115, "csv_header_name": "domestic_or_foreign_entity", "db_column_name": "domestic_or_foreign_entity", "description": "Domestic or foreign entity description"},
    {"position": 116, "csv_header_name": "dod_acquisition_program_code", "db_column_name": "dod_acquisition_program_code", "description": "DoD acquisition program code"},
    {"position": 117, "csv_header_name": "dod_acquisition_program_description", "db_column_name": "dod_acquisition_program_description", "description": "DoD acquisition program description"},
    {"position": 118, "csv_header_name": "information_technology_commercial_item_category_code", "db_column_name": "information_technology_commercial_item_category_code", "description": "IT commercial item category code"},
    {"position": 119, "csv_header_name": "information_technology_commercial_item_category", "db_column_name": "information_technology_commercial_item_category", "description": "IT commercial item category description"},
    {"position": 120, "csv_header_name": "epa_designated_product_code", "db_column_name": "epa_designated_product_code", "description": "EPA designated product code"},
    {"position": 121, "csv_header_name": "epa_designated_product", "db_column_name": "epa_designated_product", "description": "EPA designated product description"},
    {"position": 122, "csv_header_name": "country_of_product_or_service_origin_code", "db_column_name": "country_of_product_or_service_origin_code", "description": "Country of product or service origin code"},
    {"position": 123, "csv_header_name": "country_of_product_or_service_origin", "db_column_name": "country_of_product_or_service_origin", "description": "Country of product or service origin description"},
    {"position": 124, "csv_header_name": "place_of_manufacture_code", "db_column_name": "place_of_manufacture_code", "description": "Place of manufacture code"},
    {"position": 125, "csv_header_name": "place_of_manufacture", "db_column_name": "place_of_manufacture", "description": "Place of manufacture description"},
    {"position": 126, "csv_header_name": "subcontracting_plan_code", "db_column_name": "subcontracting_plan_code", "description": "Subcontracting plan code"},
    {"position": 127, "csv_header_name": "subcontracting_plan", "db_column_name": "subcontracting_plan", "description": "Subcontracting plan description"},
    {"position": 128, "csv_header_name": "extent_competed_code", "db_column_name": "extent_competed_code", "description": "Extent competed code"},
    {"position": 129, "csv_header_name": "extent_competed", "db_column_name": "extent_competed", "description": "Extent competed description"},
    {"position": 130, "csv_header_name": "solicitation_procedures_code", "db_column_name": "solicitation_procedures_code", "description": "Solicitation procedures code"},
    {"position": 131, "csv_header_name": "solicitation_procedures", "db_column_name": "solicitation_procedures", "description": "Solicitation procedures description"},
    {"position": 132, "csv_header_name": "type_of_set_aside_code", "db_column_name": "type_of_set_aside_code", "description": "Type of set-aside code"},
    {"position": 133, "csv_header_name": "type_of_set_aside", "db_column_name": "type_of_set_aside", "description": "Type of set-aside description"},
    {"position": 134, "csv_header_name": "evaluated_preference_code", "db_column_name": "evaluated_preference_code", "description": "Evaluated preference code"},
    {"position": 135, "csv_header_name": "evaluated_preference", "db_column_name": "evaluated_preference", "description": "Evaluated preference description"},
    {"position": 136, "csv_header_name": "research_code", "db_column_name": "research_code", "description": "Research code"},
    {"position": 137, "csv_header_name": "research", "db_column_name": "research", "description": "Research description"},
    {"position": 138, "csv_header_name": "fair_opportunity_limited_sources_code", "db_column_name": "fair_opportunity_limited_sources_code", "description": "Fair opportunity limited sources code"},
    {"position": 139, "csv_header_name": "fair_opportunity_limited_sources", "db_column_name": "fair_opportunity_limited_sources", "description": "Fair opportunity limited sources description"},
    {"position": 140, "csv_header_name": "other_than_full_and_open_competition_code", "db_column_name": "other_than_full_and_open_competition_code", "description": "Other than full and open competition code"},
    {"position": 141, "csv_header_name": "other_than_full_and_open_competition", "db_column_name": "other_than_full_and_open_competition", "description": "Other than full and open competition description"},
    {"position": 142, "csv_header_name": "number_of_offers_received", "db_column_name": "number_of_offers_received", "description": "Number of offers received"},
    {"position": 143, "csv_header_name": "commercial_item_acquisition_procedures_code", "db_column_name": "commercial_item_acquisition_procedures_code", "description": "Commercial item acquisition procedures code"},
    {"position": 144, "csv_header_name": "commercial_item_acquisition_procedures", "db_column_name": "commercial_item_acquisition_procedures", "description": "Commercial item acquisition procedures description"},
    {"position": 145, "csv_header_name": "small_business_competitiveness_demonstration_program", "db_column_name": "small_business_competitiveness_demonstration_program", "description": "Small business competitiveness demonstration program flag"},
    {"position": 146, "csv_header_name": "simplified_procedures_for_certain_commercial_items_code", "db_column_name": "simplified_procedures_for_certain_commercial_items_code", "description": "Simplified procedures for certain commercial items code"},
    {"position": 147, "csv_header_name": "simplified_procedures_for_certain_commercial_items", "db_column_name": "simplified_procedures_for_certain_commercial_items", "description": "Simplified procedures for certain commercial items description"},
    {"position": 148, "csv_header_name": "a76_fair_act_action_code", "db_column_name": "a76_fair_act_action_code", "description": "A-76 FAIR Act action code"},
    {"position": 149, "csv_header_name": "a76_fair_act_action", "db_column_name": "a76_fair_act_action", "description": "A-76 FAIR Act action description"},
    {"position": 150, "csv_header_name": "fed_biz_opps_code", "db_column_name": "fed_biz_opps_code", "description": "FedBizOpps code"},
    {"position": 151, "csv_header_name": "fed_biz_opps", "db_column_name": "fed_biz_opps", "description": "FedBizOpps description"},
    {"position": 152, "csv_header_name": "local_area_set_aside_code", "db_column_name": "local_area_set_aside_code", "description": "Local area set-aside code"},
    {"position": 153, "csv_header_name": "local_area_set_aside", "db_column_name": "local_area_set_aside", "description": "Local area set-aside description"},
    {"position": 154, "csv_header_name": "price_evaluation_adjustment_preference_percent_difference", "db_column_name": "price_evaluation_adjustment_preference_percent_difference", "description": "Price evaluation adjustment preference percent difference"},
    {"position": 155, "csv_header_name": "clinger_cohen_act_planning_code", "db_column_name": "clinger_cohen_act_planning_code", "description": "Clinger-Cohen Act planning code"},
    {"position": 156, "csv_header_name": "clinger_cohen_act_planning", "db_column_name": "clinger_cohen_act_planning", "description": "Clinger-Cohen Act planning description"},
    {"position": 157, "csv_header_name": "materials_supplies_articles_equipment_code", "db_column_name": "materials_supplies_articles_equipment_code", "description": "Materials, supplies, articles, equipment code"},
    {"position": 158, "csv_header_name": "materials_supplies_articles_equipment", "db_column_name": "materials_supplies_articles_equipment", "description": "Materials, supplies, articles, equipment description"},
    {"position": 159, "csv_header_name": "labor_standards_code", "db_column_name": "labor_standards_code", "description": "Labor standards code"},
    {"position": 160, "csv_header_name": "labor_standards", "db_column_name": "labor_standards", "description": "Labor standards description"},
    {"position": 161, "csv_header_name": "construction_wage_rate_requirements_code", "db_column_name": "construction_wage_rate_requirements_code", "description": "Construction wage rate requirements code"},
    {"position": 162, "csv_header_name": "construction_wage_rate_requirements", "db_column_name": "construction_wage_rate_requirements", "description": "Construction wage rate requirements description"},
    {"position": 163, "csv_header_name": "interagency_contracting_authority_code", "db_column_name": "interagency_contracting_authority_code", "description": "Interagency contracting authority code"},
    {"position": 164, "csv_header_name": "interagency_contracting_authority", "db_column_name": "interagency_contracting_authority", "description": "Interagency contracting authority description"},
    {"position": 165, "csv_header_name": "other_statutory_authority", "db_column_name": "other_statutory_authority", "description": "Other statutory authority"},
    {"position": 166, "csv_header_name": "program_acronym", "db_column_name": "program_acronym", "description": "Program acronym"},
    {"position": 167, "csv_header_name": "parent_award_type_code", "db_column_name": "parent_award_type_code", "description": "Parent award type code"},
    {"position": 168, "csv_header_name": "parent_award_type", "db_column_name": "parent_award_type", "description": "Parent award type description"},
    {"position": 169, "csv_header_name": "parent_award_single_or_multiple_code", "db_column_name": "parent_award_single_or_multiple_code", "description": "Parent award single or multiple code"},
    {"position": 170, "csv_header_name": "parent_award_single_or_multiple", "db_column_name": "parent_award_single_or_multiple", "description": "Parent award single or multiple description"},
    {"position": 171, "csv_header_name": "major_program", "db_column_name": "major_program", "description": "Major program"},
    {"position": 172, "csv_header_name": "national_interest_action_code", "db_column_name": "national_interest_action_code", "description": "National interest action code"},
    {"position": 173, "csv_header_name": "national_interest_action", "db_column_name": "national_interest_action", "description": "National interest action description"},
    {"position": 174, "csv_header_name": "cost_or_pricing_data_code", "db_column_name": "cost_or_pricing_data_code", "description": "Cost or pricing data code"},
    {"position": 175, "csv_header_name": "cost_or_pricing_data", "db_column_name": "cost_or_pricing_data", "description": "Cost or pricing data description"},
    {"position": 176, "csv_header_name": "cost_accounting_standards_clause_code", "db_column_name": "cost_accounting_standards_clause_code", "description": "Cost accounting standards clause code"},
    {"position": 177, "csv_header_name": "cost_accounting_standards_clause", "db_column_name": "cost_accounting_standards_clause", "description": "Cost accounting standards clause description"},
    {"position": 178, "csv_header_name": "government_furnished_property_code", "db_column_name": "government_furnished_property_code", "description": "Government-furnished property code"},
    {"position": 179, "csv_header_name": "government_furnished_property", "db_column_name": "government_furnished_property", "description": "Government-furnished property description"},
    {"position": 180, "csv_header_name": "sea_transportation_code", "db_column_name": "sea_transportation_code", "description": "Sea transportation code"},
    {"position": 181, "csv_header_name": "sea_transportation", "db_column_name": "sea_transportation", "description": "Sea transportation description"},
    {"position": 182, "csv_header_name": "undefinitized_action_code", "db_column_name": "undefinitized_action_code", "description": "Undefinitized action code"},
    {"position": 183, "csv_header_name": "undefinitized_action", "db_column_name": "undefinitized_action", "description": "Undefinitized action description"},
    {"position": 184, "csv_header_name": "consolidated_contract_code", "db_column_name": "consolidated_contract_code", "description": "Consolidated contract code"},
    {"position": 185, "csv_header_name": "consolidated_contract", "db_column_name": "consolidated_contract", "description": "Consolidated contract description"},
    {"position": 186, "csv_header_name": "performance_based_service_acquisition_code", "db_column_name": "performance_based_service_acquisition_code", "description": "Performance-based service acquisition code"},
    {"position": 187, "csv_header_name": "performance_based_service_acquisition", "db_column_name": "performance_based_service_acquisition", "description": "Performance-based service acquisition description"},
    {"position": 188, "csv_header_name": "multi_year_contract_code", "db_column_name": "multi_year_contract_code", "description": "Multi-year contract code"},
    {"position": 189, "csv_header_name": "multi_year_contract", "db_column_name": "multi_year_contract", "description": "Multi-year contract description"},
    {"position": 190, "csv_header_name": "contract_financing_code", "db_column_name": "contract_financing_code", "description": "Contract financing code"},
    {"position": 191, "csv_header_name": "contract_financing", "db_column_name": "contract_financing", "description": "Contract financing description"},
    {"position": 192, "csv_header_name": "purchase_card_as_payment_method_code", "db_column_name": "purchase_card_as_payment_method_code", "description": "Purchase card as payment method code"},
    {"position": 193, "csv_header_name": "purchase_card_as_payment_method", "db_column_name": "purchase_card_as_payment_method", "description": "Purchase card as payment method description"},
    {"position": 194, "csv_header_name": "contingency_humanitarian_or_peacekeeping_operation_code", "db_column_name": "contingency_humanitarian_or_peacekeeping_operation_code", "description": "Contingency humanitarian or peacekeeping operation code"},
    {"position": 195, "csv_header_name": "contingency_humanitarian_or_peacekeeping_operation", "db_column_name": "contingency_humanitarian_or_peacekeeping_operation", "description": "Contingency humanitarian or peacekeeping operation description"},
    {"position": 196, "csv_header_name": "alaskan_native_corporation_owned_firm", "db_column_name": "alaskan_native_corporation_owned_firm", "description": "Alaskan Native corporation-owned firm flag"},
    {"position": 197, "csv_header_name": "american_indian_owned_business", "db_column_name": "american_indian_owned_business", "description": "American Indian-owned business flag"},
    {"position": 198, "csv_header_name": "indian_tribe_federally_recognized", "db_column_name": "indian_tribe_federally_recognized", "description": "Federally recognized Indian tribe flag"},
    {"position": 199, "csv_header_name": "native_hawaiian_organization_owned_firm", "db_column_name": "native_hawaiian_organization_owned_firm", "description": "Native Hawaiian organization-owned firm flag"},
    {"position": 200, "csv_header_name": "tribally_owned_firm", "db_column_name": "tribally_owned_firm", "description": "Tribally owned firm flag"},
    {"position": 201, "csv_header_name": "veteran_owned_business", "db_column_name": "veteran_owned_business", "description": "Veteran-owned business flag"},
    {"position": 202, "csv_header_name": "service_disabled_veteran_owned_business", "db_column_name": "service_disabled_veteran_owned_business", "description": "Service-disabled veteran-owned business flag"},
    {"position": 203, "csv_header_name": "woman_owned_business", "db_column_name": "woman_owned_business", "description": "Woman-owned business flag"},
    {"position": 204, "csv_header_name": "women_owned_small_business", "db_column_name": "women_owned_small_business", "description": "Women-owned small business flag"},
    {"position": 205, "csv_header_name": "economically_disadvantaged_women_owned_small_business", "db_column_name": "economically_disadvantaged_women_owned_small_business", "description": "Economically disadvantaged women-owned small business flag"},
    {"position": 206, "csv_header_name": "joint_venture_women_owned_small_business", "db_column_name": "joint_venture_women_owned_small_business", "description": "Joint venture women-owned small business flag"},
    {"position": 207, "csv_header_name": "joint_venture_economic_disadvantaged_women_owned_small_bus", "db_column_name": "joint_venture_economic_disadvantaged_women_owned_small_bus", "description": "Joint venture economically disadvantaged women-owned small business flag"},
    {"position": 208, "csv_header_name": "minority_owned_business", "db_column_name": "minority_owned_business", "description": "Minority-owned business flag"},
    {"position": 209, "csv_header_name": "subcontinent_asian_asian_indian_american_owned_business", "db_column_name": "subcontinent_asian_asian_indian_american_owned_business", "description": "Subcontinent Asian/Asian Indian American-owned business flag"},
    {"position": 210, "csv_header_name": "asian_pacific_american_owned_business", "db_column_name": "asian_pacific_american_owned_business", "description": "Asian Pacific American-owned business flag"},
    {"position": 211, "csv_header_name": "black_american_owned_business", "db_column_name": "black_american_owned_business", "description": "Black American-owned business flag"},
    {"position": 212, "csv_header_name": "hispanic_american_owned_business", "db_column_name": "hispanic_american_owned_business", "description": "Hispanic American-owned business flag"},
    {"position": 213, "csv_header_name": "native_american_owned_business", "db_column_name": "native_american_owned_business", "description": "Native American-owned business flag"},
    {"position": 214, "csv_header_name": "other_minority_owned_business", "db_column_name": "other_minority_owned_business", "description": "Other minority-owned business flag"},
    {"position": 215, "csv_header_name": "contracting_officers_determination_of_business_size", "db_column_name": "contracting_officers_determination_of_business_size", "description": "Contracting officer determination of business size"},
    {"position": 216, "csv_header_name": "contracting_officers_determination_of_business_size_code", "db_column_name": "contracting_officers_determination_of_business_size_code", "description": "Contracting officer determination of business size code"},
    {"position": 217, "csv_header_name": "emerging_small_business", "db_column_name": "emerging_small_business", "description": "Emerging small business flag"},
    {"position": 218, "csv_header_name": "community_developed_corporation_owned_firm", "db_column_name": "community_developed_corporation_owned_firm", "description": "Community developed corporation-owned firm flag"},
    {"position": 219, "csv_header_name": "labor_surplus_area_firm", "db_column_name": "labor_surplus_area_firm", "description": "Labor surplus area firm flag"},
    {"position": 220, "csv_header_name": "us_federal_government", "db_column_name": "us_federal_government", "description": "US federal government flag"},
    {"position": 221, "csv_header_name": "federally_funded_research_and_development_corp", "db_column_name": "federally_funded_research_and_development_corp", "description": "Federally funded research and development corp flag"},
    {"position": 222, "csv_header_name": "federal_agency", "db_column_name": "federal_agency", "description": "Federal agency flag"},
    {"position": 223, "csv_header_name": "us_state_government", "db_column_name": "us_state_government", "description": "US state government flag"},
    {"position": 224, "csv_header_name": "us_local_government", "db_column_name": "us_local_government", "description": "US local government flag"},
    {"position": 225, "csv_header_name": "city_local_government", "db_column_name": "city_local_government", "description": "City local government flag"},
    {"position": 226, "csv_header_name": "county_local_government", "db_column_name": "county_local_government", "description": "County local government flag"},
    {"position": 227, "csv_header_name": "inter_municipal_local_government", "db_column_name": "inter_municipal_local_government", "description": "Inter-municipal local government flag"},
    {"position": 228, "csv_header_name": "local_government_owned", "db_column_name": "local_government_owned", "description": "Local government-owned flag"},
    {"position": 229, "csv_header_name": "municipality_local_government", "db_column_name": "municipality_local_government", "description": "Municipality local government flag"},
    {"position": 230, "csv_header_name": "school_district_local_government", "db_column_name": "school_district_local_government", "description": "School district local government flag"},
    {"position": 231, "csv_header_name": "township_local_government", "db_column_name": "township_local_government", "description": "Township local government flag"},
    {"position": 232, "csv_header_name": "us_tribal_government", "db_column_name": "us_tribal_government", "description": "US tribal government flag"},
    {"position": 233, "csv_header_name": "foreign_government", "db_column_name": "foreign_government", "description": "Foreign government flag"},
    {"position": 234, "csv_header_name": "organizational_type", "db_column_name": "organizational_type", "description": "Organizational type"},
    {"position": 235, "csv_header_name": "corporate_entity_not_tax_exempt", "db_column_name": "corporate_entity_not_tax_exempt", "description": "Corporate entity not tax-exempt flag"},
    {"position": 236, "csv_header_name": "corporate_entity_tax_exempt", "db_column_name": "corporate_entity_tax_exempt", "description": "Corporate entity tax-exempt flag"},
    {"position": 237, "csv_header_name": "partnership_or_limited_liability_partnership", "db_column_name": "partnership_or_limited_liability_partnership", "description": "Partnership or limited liability partnership flag"},
    {"position": 238, "csv_header_name": "sole_proprietorship", "db_column_name": "sole_proprietorship", "description": "Sole proprietorship flag"},
    {"position": 239, "csv_header_name": "small_agricultural_cooperative", "db_column_name": "small_agricultural_cooperative", "description": "Small agricultural cooperative flag"},
    {"position": 240, "csv_header_name": "international_organization", "db_column_name": "international_organization", "description": "International organization flag"},
    {"position": 241, "csv_header_name": "us_government_entity", "db_column_name": "us_government_entity", "description": "US government entity flag"},
    {"position": 242, "csv_header_name": "community_development_corporation", "db_column_name": "community_development_corporation", "description": "Community development corporation flag"},
    {"position": 243, "csv_header_name": "domestic_shelter", "db_column_name": "domestic_shelter", "description": "Domestic shelter flag"},
    {"position": 244, "csv_header_name": "educational_institution", "db_column_name": "educational_institution", "description": "Educational institution flag"},
    {"position": 245, "csv_header_name": "foundation", "db_column_name": "foundation", "description": "Foundation flag"},
    {"position": 246, "csv_header_name": "hospital_flag", "db_column_name": "hospital_flag", "description": "Hospital flag"},
    {"position": 247, "csv_header_name": "manufacturer_of_goods", "db_column_name": "manufacturer_of_goods", "description": "Manufacturer of goods flag"},
    {"position": 248, "csv_header_name": "veterinary_hospital", "db_column_name": "veterinary_hospital", "description": "Veterinary hospital flag"},
    {"position": 249, "csv_header_name": "hispanic_servicing_institution", "db_column_name": "hispanic_servicing_institution", "description": "Hispanic-servicing institution flag"},
    {"position": 250, "csv_header_name": "receives_contracts", "db_column_name": "receives_contracts", "description": "Receives contracts flag"},
    {"position": 251, "csv_header_name": "receives_financial_assistance", "db_column_name": "receives_financial_assistance", "description": "Receives financial assistance flag"},
    {"position": 252, "csv_header_name": "receives_contracts_and_financial_assistance", "db_column_name": "receives_contracts_and_financial_assistance", "description": "Receives both contracts and financial assistance flag"},
    {"position": 253, "csv_header_name": "airport_authority", "db_column_name": "airport_authority", "description": "Airport authority flag"},
    {"position": 254, "csv_header_name": "council_of_governments", "db_column_name": "council_of_governments", "description": "Council of governments flag"},
    {"position": 255, "csv_header_name": "housing_authorities_public_tribal", "db_column_name": "housing_authorities_public_tribal", "description": "Housing authorities public/tribal flag"},
    {"position": 256, "csv_header_name": "interstate_entity", "db_column_name": "interstate_entity", "description": "Interstate entity flag"},
    {"position": 257, "csv_header_name": "planning_commission", "db_column_name": "planning_commission", "description": "Planning commission flag"},
    {"position": 258, "csv_header_name": "port_authority", "db_column_name": "port_authority", "description": "Port authority flag"},
    {"position": 259, "csv_header_name": "transit_authority", "db_column_name": "transit_authority", "description": "Transit authority flag"},
    {"position": 260, "csv_header_name": "subchapter_scorporation", "db_column_name": "subchapter_scorporation", "description": "Subchapter S corporation flag"},
    {"position": 261, "csv_header_name": "limited_liability_corporation", "db_column_name": "limited_liability_corporation", "description": "Limited liability corporation flag"},
    {"position": 262, "csv_header_name": "foreign_owned", "db_column_name": "foreign_owned", "description": "Foreign-owned flag"},
    {"position": 263, "csv_header_name": "for_profit_organization", "db_column_name": "for_profit_organization", "description": "For-profit organization flag"},
    {"position": 264, "csv_header_name": "nonprofit_organization", "db_column_name": "nonprofit_organization", "description": "Nonprofit organization flag"},
    {"position": 265, "csv_header_name": "other_not_for_profit_organization", "db_column_name": "other_not_for_profit_organization", "description": "Other not-for-profit organization flag"},
    {"position": 266, "csv_header_name": "the_ability_one_program", "db_column_name": "the_ability_one_program", "description": "The AbilityOne Program flag"},
    {"position": 267, "csv_header_name": "private_university_or_college", "db_column_name": "private_university_or_college", "description": "Private university or college flag"},
    {"position": 268, "csv_header_name": "state_controlled_institution_of_higher_learning", "db_column_name": "state_controlled_institution_of_higher_learning", "description": "State-controlled institution of higher learning flag"},
    {"position": 269, "csv_header_name": "1862_land_grant_college", "db_column_name": "col_1862_land_grant_college", "description": "1862 land-grant college flag (CSV header: 1862_land_grant_college)"},
    {"position": 270, "csv_header_name": "1890_land_grant_college", "db_column_name": "col_1890_land_grant_college", "description": "1890 land-grant college flag (CSV header: 1890_land_grant_college)"},
    {"position": 271, "csv_header_name": "1994_land_grant_college", "db_column_name": "col_1994_land_grant_college", "description": "1994 land-grant college flag (CSV header: 1994_land_grant_college)"},
    {"position": 272, "csv_header_name": "minority_institution", "db_column_name": "minority_institution", "description": "Minority institution flag"},
    {"position": 273, "csv_header_name": "historically_black_college", "db_column_name": "historically_black_college", "description": "Historically Black college flag"},
    {"position": 274, "csv_header_name": "tribal_college", "db_column_name": "tribal_college", "description": "Tribal college flag"},
    {"position": 275, "csv_header_name": "alaskan_native_servicing_institution", "db_column_name": "alaskan_native_servicing_institution", "description": "Alaskan Native-servicing institution flag"},
    {"position": 276, "csv_header_name": "native_hawaiian_servicing_institution", "db_column_name": "native_hawaiian_servicing_institution", "description": "Native Hawaiian-servicing institution flag"},
    {"position": 277, "csv_header_name": "school_of_forestry", "db_column_name": "school_of_forestry", "description": "School of forestry flag"},
    {"position": 278, "csv_header_name": "veterinary_college", "db_column_name": "veterinary_college", "description": "Veterinary college flag"},
    {"position": 279, "csv_header_name": "dot_certified_disadvantage", "db_column_name": "dot_certified_disadvantage", "description": "DOT-certified disadvantaged business flag"},
    {"position": 280, "csv_header_name": "self_certified_small_disadvantaged_business", "db_column_name": "self_certified_small_disadvantaged_business", "description": "Self-certified small disadvantaged business flag"},
    {"position": 281, "csv_header_name": "small_disadvantaged_business", "db_column_name": "small_disadvantaged_business", "description": "Small disadvantaged business flag"},
    {"position": 282, "csv_header_name": "c8a_program_participant", "db_column_name": "c8a_program_participant", "description": "8(a) program participant flag"},
    {"position": 283, "csv_header_name": "historically_underutilized_business_zone_hubzone_firm", "db_column_name": "historically_underutilized_business_zone_hubzone_firm", "description": "HUBZone firm flag"},
    {"position": 284, "csv_header_name": "sba_certified_8a_joint_venture", "db_column_name": "sba_certified_8a_joint_venture", "description": "SBA-certified 8(a) joint venture flag"},
    {"position": 285, "csv_header_name": "highly_compensated_officer_1_name", "db_column_name": "highly_compensated_officer_1_name", "description": "Highly compensated officer 1 name"},
    {"position": 286, "csv_header_name": "highly_compensated_officer_1_amount", "db_column_name": "highly_compensated_officer_1_amount", "description": "Highly compensated officer 1 amount"},
    {"position": 287, "csv_header_name": "highly_compensated_officer_2_name", "db_column_name": "highly_compensated_officer_2_name", "description": "Highly compensated officer 2 name"},
    {"position": 288, "csv_header_name": "highly_compensated_officer_2_amount", "db_column_name": "highly_compensated_officer_2_amount", "description": "Highly compensated officer 2 amount"},
    {"position": 289, "csv_header_name": "highly_compensated_officer_3_name", "db_column_name": "highly_compensated_officer_3_name", "description": "Highly compensated officer 3 name"},
    {"position": 290, "csv_header_name": "highly_compensated_officer_3_amount", "db_column_name": "highly_compensated_officer_3_amount", "description": "Highly compensated officer 3 amount"},
    {"position": 291, "csv_header_name": "highly_compensated_officer_4_name", "db_column_name": "highly_compensated_officer_4_name", "description": "Highly compensated officer 4 name"},
    {"position": 292, "csv_header_name": "highly_compensated_officer_4_amount", "db_column_name": "highly_compensated_officer_4_amount", "description": "Highly compensated officer 4 amount"},
    {"position": 293, "csv_header_name": "highly_compensated_officer_5_name", "db_column_name": "highly_compensated_officer_5_name", "description": "Highly compensated officer 5 name"},
    {"position": 294, "csv_header_name": "highly_compensated_officer_5_amount", "db_column_name": "highly_compensated_officer_5_amount", "description": "Highly compensated officer 5 amount"},
    {"position": 295, "csv_header_name": "usaspending_permalink", "db_column_name": "usaspending_permalink", "description": "USASpending.gov permalink URL"},
    {"position": 296, "csv_header_name": "initial_report_date", "db_column_name": "initial_report_date", "description": "Date the transaction was initially reported"},
    {"position": 297, "csv_header_name": "last_modified_date", "db_column_name": "last_modified_date", "description": "Date the transaction was last modified"},
]

USASPENDING_COLUMN_COUNT: int = len(USASPENDING_COLUMNS)

USASPENDING_DB_COLUMN_NAMES: list[str] = [col['db_column_name'] for col in USASPENDING_COLUMNS]

USASPENDING_CSV_TO_DB_MAP: dict[str, str] = {col['csv_header_name']: col['db_column_name'] for col in USASPENDING_COLUMNS}

USASPENDING_DELTA_EXTRA_COLUMNS: list[dict] = [
    {"position": -2, "csv_header_name": "correction_delete_ind", "db_column_name": "correction_delete_ind", "description": "Delta indicator: empty=update, C=correction, D=deletion"},
    {"position": -1, "csv_header_name": "agency_id", "db_column_name": "agency_id", "description": "Agency routing code (delta files only)"},
]

USASPENDING_DELTA_COLUMN_COUNT: int = USASPENDING_COLUMN_COUNT + len(USASPENDING_DELTA_EXTRA_COLUMNS)


# ── Self-test ──────────────────────────────────────────────────────────────

if __name__ == '__main__':
    assert USASPENDING_COLUMN_COUNT == 297, f'Expected 297, got {USASPENDING_COLUMN_COUNT}'
    assert USASPENDING_DELTA_COLUMN_COUNT == 299, f'Expected 299, got {USASPENDING_DELTA_COLUMN_COUNT}'
    assert USASPENDING_COLUMNS[0]['db_column_name'] == 'contract_transaction_unique_key'
    assert USASPENDING_COLUMNS[-1]['db_column_name'] == 'last_modified_date'
    assert len(set(USASPENDING_DB_COLUMN_NAMES)) == 297, 'Duplicate db column names'
    print(f'USASpending column map: {USASPENDING_COLUMN_COUNT} columns OK')
    print(f'  First: {USASPENDING_COLUMNS[0]["db_column_name"]}')
    print(f'  Last:  {USASPENDING_COLUMNS[-1]["db_column_name"]}')
    print(f'  Delta: {USASPENDING_DELTA_COLUMN_COUNT} columns')
