"""
Provider enum value constants extracted from API reference documentation.

Each constant is an immutable tuple of exact, case-sensitive values accepted
by the provider. Accompanying frozensets and reverse-lookup dicts support
case-insensitive matching in the resolution engine.
"""

# ---------------------------------------------------------------------------
# Prospeo
# ---------------------------------------------------------------------------

PROSPEO_SENIORITIES: tuple[str, ...] = (
    "Founder/Owner",
    "C-Suite",
    "Partner",
    "Vice President",
    "Head",
    "Director",
    "Manager",
    "Senior",
    "Entry",
    "Intern",
)

PROSPEO_DEPARTMENTS: tuple[str, ...] = (
    # C-Suite
    "Chief Executive",
    "Finance Executive",
    "Founder",
    "Human Resources Executive",
    "Information Technology Executive",
    "Legal Executive",
    "Marketing Executive",
    "Medical & Health Executive",
    "Operations Executive",
    "Sales Leader",
    # Product
    "Product Development",
    "Product Management",
    "All Product",
    # Engineering & Technical
    "Engineering & Technical",
    "Artificial Intelligence / Machine Learning",
    "Bioengineering",
    "Biometrics",
    "Business Intelligence",
    "Chemical Engineering",
    "Data Science & Analysis",
    "DevOps",
    "Digital Transformation",
    "Emerging Technology / Innovation",
    "Industrial Engineering",
    "Mechanic",
    "Mobile Development",
    "Project Management",
    "Research & Development",
    "Scrum Master / Agile Coach",
    "Software Development",
    "Technician",
    "Technology Operations",
    "Test / Quality Assurance",
    # Design
    "All Design",
    "Graphic / Visual / Brand Design",
    # Education & Coaching
    "Teacher",
    "Superintendent",
    "Professor",
    "Coach / Trainer",
    # Finance
    "Financial Reporting",
    "Financial Systems",
    "Accounting",
    "Finance & Banking",
    "Financial Planning, Strategy & Analysis",
    "Internal Audit & Control",
    "Investor Relations",
    "Mergers & Acquisitions",
    "Real Estate Finance",
    "Financial Risk",
    "Sourcing / Procurement",
    "Tax",
    "Treasury",
    # Human Resources
    "Compensation & Benefits",
    "Culture, Diversity & Inclusion",
    "Health & Safety",
    "All Human Resources",
    "HR Business Partner",
    "Learning & Development",
    "Organizational Development",
    "Recruiting & Talent Acquisition",
    "Talent Management",
    "Workforce Management",
    "People Operations",
    # Information Technology
    "Cloud Engineering",
    "Data Center",
    "Data Warehouse",
    "Database Administration",
    "eCommerce Development",
    "Help Desk / Desktop Services",
    "Information Security",
    "IT Asset Management",
    "IT Audit / IT Compliance",
    "IT Recruitement",
    "IT Procurement",
    "IT Strategy",
    "IT Training",
    "Networking",
    "Technical Lead",
    "Quality Assurance",
    "Retail / Store Systems",
    "Servers",
    "Disaster Recovery",
    "Telecommunications",
    # Legal
    "Compliance",
    "Contracts",
    "Corporate Secretary",
    "eDiscovery",
    "Ethics",
    "Governance",
    "Governmental Affairs & Regulatory Law",
    "Intellectual Property & Patent",
    "Labor & Employment",
    "Lawyer / Attorney",
    "All Legal",
    "Legal Counsel",
    "Legal Operations",
    "Litigation",
    "Privacy",
    # Marketing
    "Advertising",
    "Brand Management",
    "Content Marketing",
    "Customer Experience",
    "Customer Marketing",
    "Growth & Demand Generation",
    "Digital Marketing",
    "eCommerce Marketing",
    "Event & Field Marketing",
    "Lead Generation",
    "Marketing Operations",
    "Product Marketing",
    "Public Relations",
    "SEO",
    "Social Media Marketing",
    "Technical Marketing",
    # Medical & Health
    "Anesthesiology",
    "Chiropractics",
    "Clinical Systems",
    "Dentistry",
    "Dermatology",
    "Doctors / Physicians",
    "Epidemiology",
    "Fire Responder",
    "Infectious Disease",
    "Medical Administration",
    "Medical Education & Training",
    "Clinical Research",
    "Neurology",
    "Nursing",
    "Nutrition & Dietetics",
    "Obstetrics / Gynecology",
    "Oncology",
    "Opthalmology",
    "Optometry",
    "Orthopedics",
    "Radiology",
    "Public Health",
    "Psychology",
    "Psychiatry",
    "Physical Therapy",
    "Pharmacy",
    "Pediatrics",
    "Pathology",
    # Consulting
    "Consultant",
    # Sales
    "All Sales",
    "Sales Training",
    "Sales Operations",
    "Sales Engineering",
    "Sales Enablement",
    "Revenue Operations",
    "Partnerships",
    "Sales Development",
    "Account Executive",
    "Field / Outside Sales",
    "Customer Success",
    "Customer Retention & Development",
    "Channel Sales",
    "Account Management",
    # Operations
    "Supply Chain",
    "Store Operations",
    "Safety",
    "Real Estate",
    "Quality Management",
    "Physical Security",
    "Office Operations",
    "Logistics",
    "Leasing",
    "Facilities Management",
    "Customer Service / Support",
    "Corporate Strategy",
    "Construction",
    "Call Center",
)

PROSPEO_INDUSTRIES: tuple[str, ...] = (
    "IT Services and IT Consulting",
    "Construction",
    "Business Consulting and Services",
    "General Retail",
    "Advertising Services",
    "Real Estate",
    "Software Development",
    "Medical Practices",
    "Financial Services",
    "Technology, Information and Internet",
    "Restaurants",
    "Hospitals and Health Care",
    "Wellness and Fitness Services",
    "Design Services",
    "Non-profit Organizations",
    "Individual and Family Services",
    "Hospitality",
    "Appliances, Electrical, and Electronics Manufacturing",
    "Motor Vehicle Manufacturing",
    "Professional Training and Coaching",
    "Food and Beverage Services",
    "Education Administration Programs",
    "Consumer Services",
    "Accounting",
    "General Wholesale",
    "Civic and Social Organizations",
    "Architecture and Planning",
    "Truck and Railroad Transportation",
    "Spectator Sports",
    "Entertainment Providers",
    "Retail Apparel and Fashion",
    "Higher Education",
    "Industrial Machinery Manufacturing",
    "Insurance",
    "Machinery Manufacturing",
    "Legal Services",
    "General Manufacturing",
    "Events Services",
    "Travel Arrangements",
    "Human Resources Services",
    "Law Practice",
    "Media Production and Publishing",
    "Food and Beverage Manufacturing",
    "Staffing and Recruiting",
    "Marketing Services",
    "Renewable Energy",
    "Research Services",
    "Facilities Services",
    "Environmental Services",
    "Telecommunications",
    "Transportation, Logistics, Supply Chain and Storage",
    "Electric Power Generation",
    "E-Learning Providers",
    "Oil, Gas, and Mining",
    "Arts and Crafts",
    "Photography",
    "Venture Capital and Private Equity Principals",
    "Music",
    "Retail Office Equipment",
    "Farming",
    "Wholesale Building Materials",
    "Furniture and Home Furnishings Manufacturing",
    "Government Administration",
    "Investment Management",
    "Civil Engineering",
    "Primary and Secondary Education",
    "Medical Equipment Manufacturing",
    "Textile Manufacturing",
    "Public Relations and Communications Services",
    "Printing Services",
    "Religious Institutions",
    "Artists and Writers",
    "Personal Care Product Manufacturing",
    "International Trade and Development",
    "Mental Health Care",
    "Chemical Manufacturing",
    "Pharmaceutical Manufacturing",
    "Utilities",
    "Information Services",
    "Security and Investigations",
    "Wholesale Import and Export",
    "Banking",
    "Biotechnology Research",
    "Recreational Facilities",
    "Automation Machinery Manufacturing",
    "Plastics Manufacturing",
    "Automotive",
    "Retail Groceries",
    "Freight and Package Transportation",
    "Computer and Network Security",
    "Computer Games",
    "Veterinary Services",
    "Airlines and Aviation",
    "Maritime Transportation",
    "Executive Offices",
    "Sporting Goods Manufacturing",
    "Market Research",
    "Mechanical or Industrial Engineering",
    "Aviation and Aerospace Component Manufacturing",
    "Strategic Management Services",
    "Consumer Goods",
    "Engineering Services",
    "Museums, Historical Sites, and Zoos",
    "Investment, Funds and Trusts",
    "Philanthropic Fundraising Services",
    "Human Resources",
    "Computer Hardware",
    "E-Learning",
    "Translation and Localization",
    "Public Safety",
    "Business Supplies and Equipment",
    "Defense and Space Manufacturing",
    "Glass, Ceramics and Concrete Manufacturing",
    "Warehousing and Storage",
    "Alternative Medicine",
    "Animation and Post-production",
    "Think Tanks",
    "Semiconductor Manufacturing",
    "Building Materials",
    "Capital Markets",
    "Interior Design",
    "Political Organizations",
    "Fundraising",
    "Law Enforcement",
    "Cosmetics",
    "Wireless Services",
    "Sports Teams and Clubs",
    "Retail Health and Personal Care Products",
    "Professional Services",
    "Social Networking Platforms",
    "Dairy Product Manufacturing",
    "Gambling Facilities and Casinos",
    "Internet Marketplace Platforms",
    "Shipbuilding",
    "Luxury Goods and Jewelry",
    "Libraries",
    "Ranching and Fisheries",
    "Online and Mail Order Retail",
    "Community Services",
    "Blockchain Services",
    "Food and Beverage Retail",
    "Retail Motor Vehicles",
    "Data Infrastructure and Analytics",
    "Wine and Spirits",
    "Sports and Recreation Instruction",
    "Paper and Forest Products",
    "Agriculture, Construction, Mining Machinery Manufacturing",
    "Home Health Care Services",
    "Vehicle Repair and Maintenance",
    "Business Content",
    "General Repair and Maintenance",
    "Maritime",
    "Packaging and Containers",
    "Industry Associations",
    "Retail Furniture and Home Furnishings",
    "Tobacco Manufacturing",
    "Pet Services",
    "Landscaping Services",
    "Alternative Dispute Resolution",
    "Dentists",
    "Wholesale Food and Beverage",
    "Fabricated Metal Products",
    "Aviation & Aerospace",
    "Railroad Equipment Manufacturing",
    "Mobile Gaming Apps",
    "Administrative and Support Services",
    "Apparel Manufacturing",
    "Nanotechnology Research",
    "Specialty Trade Contractors",
    "Janitorial Services",
    "Physical, Occupational and Speech Therapists",
    "Medical and Diagnostic Laboratories",
    "Professional Organizations",
    "Philanthropy",
    "Digital Accessibility Services",
    "Fashion Accessories Manufacturing",
    "Semiconductors",
    "Wholesale Motor Vehicles and Parts",
    "HVAC and Refrigeration Equipment Manufacturing",
    "Schools",
    "Wood Product Manufacturing",
    "Fire Protection",
    "Retail Office Supplies and Gifts",
    "Equipment Rental Services",
    "Movies, Videos and Sound",
    "Ground Passenger Transportation",
    "Wholesale Hardware, Plumbing, Heating Equipment",
    "Housing and Community Development",
    "Robotics Engineering",
    "Wholesale Chemical and Allied Products",
    "Building Finishing Contractors",
    "Child Day Care Services",
    "Radio and Television Broadcasting",
    "Paint, Coating, and Adhesive Manufacturing",
    "Building Structure and Exterior Contractors",
    "Retail Pharmacies",
    "Retail Building Materials and Garden Equipment",
    "Waste Treatment and Disposal",
    "Wholesale Machinery",
    "Metal Treatments",
    "Accommodation Services",
    "Horticulture",
    "Water Supply and Irrigation Systems",
    "Building Equipment Contractors",
    "Waste Collection",
    "Executive Search Services",
    "Telephone Call Centers",
    "Mobile Food Services",
    "Data Security Software Products",
    "Taxi and Limousine Services",
    "Retail Florists",
    "Metalworking Machinery Manufacturing",
    "Plastics and Rubber Product Manufacturing",
    "Climate Technology Product Manufacturing",
    "Golf Courses and Country Clubs",
    "Loan Brokers",
    "Water, Waste, Steam, and Air Conditioning Services",
    "Office Administration",
    "Wholesale Metals and Minerals",
    "Construction Hardware Manufacturing",
    "Surveying and Mapping Services",
    "Air, Water, and Waste Program Management",
    "Measuring and Control Instrument Manufacturing",
    "Leather Product Manufacturing",
    "Animal Feed Manufacturing",
    "Wholesale Furniture and Home Furnishings",
    "Wholesale Recyclable Materials",
    "Wholesale Drugs and Sundries",
    "Theater Companies",
    "Wholesale Apparel and Sewing Supplies",
    "Wholesale Computer Equipment",
    "Household, Laundry and Drycleaning Services",
    "Distilleries",
    "Breweries",
    "Wineries",
    "Optometrists",
    "Dance Companies",
    "Retail Recyclable Materials & Used Merchandise",
    "Utility System Construction",
    "Vocational Rehabilitation Services",
    "Amusement Parks and Arcades",
    "Retail Musical Instruments",
    "Turned Products and Fastener Manufacturing",
    "Engines and Power Transmission Equipment Manufacturing",
    "Transportation Equipment Manufacturing",
    "Collection Agencies",
    "Utilities Administration",
    "Credit Intermediation",
    "Housing and Socio-Economic Programs",
    "Securities and Commodity Exchanges",
    "Boilers, Tanks, and Shipping Container Manufacturing",
    "Claims Adjusting, Actuarial Services",
    "Ambulance Services",
    "Mattress and Blinds Manufacturing",
    "Regenerative Design",
    "Primary Metal Manufacturing",
)

PROSPEO_EMPLOYEE_RANGES: tuple[str, ...] = (
    "1-10",
    "11-20",
    "21-50",
    "51-100",
    "101-200",
    "201-500",
    "501-1000",
    "1001-2000",
    "2001-5000",
    "5001-10000",
    "10000+",
)

# ---------------------------------------------------------------------------
# BlitzAPI
# ---------------------------------------------------------------------------

BLITZAPI_JOB_LEVELS: tuple[str, ...] = (
    "C-Team",
    "VP",
    "Director",
    "Manager",
    "Staff",
    "Other",
)

BLITZAPI_JOB_FUNCTIONS: tuple[str, ...] = (
    "Advertising & Marketing",
    "Art, Culture and Creative Professionals",
    "Construction",
    "Customer/Client Service",
    "Education",
    "Engineering",
    "Finance & Accounting",
    "General Business & Management",
    "Healthcare & Human Services",
    "Human Resources",
    "Information Technology",
    "Legal",
    "Manufacturing & Production",
    "Operations",
    "Other",
    "Public Administration & Safety",
    "Purchasing",
    "Research & Development",
    "Sales & Business Development",
    "Science",
    "Supply Chain & Logistics",
    "Writing/Editing",
)

BLITZAPI_INDUSTRIES: tuple[str, ...] = (
    "Abrasives and Nonmetallic Minerals Manufacturing",
    "Accessible Architecture and Design",
    "Accessible Hardware Manufacturing",
    "Accommodation and Food Services",
    "Accounting",
    "Administration of Justice",
    "Administrative and Support Services",
    "Advertising Services",
    "Agricultural Chemical Manufacturing",
    "Agriculture; Construction; Mining Machinery Manufacturing",
    "Air; Water; and Waste Program Management",
    "Airlines and Aviation",
    "Airlines/Aviation",
    "Alternative Dispute Resolution",
    "Alternative Fuel Vehicle Manufacturing",
    "Alternative Medicine",
    "Ambulance Services",
    "Amusement Parks and Arcades",
    "Animal Feed Manufacturing",
    "Animation",
    "Animation and Post-production",
    "Apparel Manufacturing",
    "Apparel and Fashion",
    "Appliances; Electrical; and Electronics Manufacturing",
    "Architectural and Structural Metal Manufacturing",
    "Architecture and Planning",
    "Armed Forces",
    "Artificial Rubber and Synthetic Fiber Manufacturing",
    "Artists and Writers",
    "Arts and Crafts",
    "Audio and Video Equipment Manufacturing",
    "Automation Machinery Manufacturing",
    "Automotive",
    "Aviation and Aerospace",
    "Aviation and Aerospace Component Manufacturing",
    "Baked Goods Manufacturing",
    "Banking",
    "Bars; Taverns; and Nightclubs",
    "Bed-and-Breakfasts; Hostels; Homestays",
    "Beverage Manufacturing",
    "Biomass Electric Power Generation",
    "Biotechnology",
    "Biotechnology Research",
    "Blockchain Services",
    "Blogs",
    "Boilers; Tanks; and Shipping Container Manufacturing",
    "Book Publishing",
    "Book and Periodical Publishing",
    "Breweries",
    "Broadcast Media",
    "Broadcast Media Production and Distribution",
    "Building Construction",
    "Building Equipment Contractors",
    "Building Finishing Contractors",
    "Building Materials",
    "Building Structure and Exterior Contractors",
    "Business Consulting and Services",
    "Business Content",
    "Business Intelligence Platforms",
    "Business Supplies and Equipment",
    "Cable and Satellite Programming",
    "Capital Markets",
    "Caterers",
    "Chemical Manufacturing",
    "Chemical Raw Materials Manufacturing",
    "Chemicals",
    "Child Day Care Services",
    "Chiropractors",
    "Circuses and Magic Shows",
    "Civic and Social Organization",
    "Civic and Social Organizations",
    "Civil Engineering",
    "Claims Adjusting; Actuarial Services",
    "Clay and Refractory Products Manufacturing",
    "Climate Data and Analytics",
    "Climate Technology Product Manufacturing",
    "Coal Mining",
    "Collection Agencies",
    "Commercial Real Estate",
    "Commercial and Industrial Equipment Rental",
    "Commercial and Industrial Machinery Maintenance",
    "Commercial and Service Industry Machinery Manufacturing",
    "Communications Equipment Manufacturing",
    "Community Development and Urban Planning",
    "Community Services",
    "Computer Games",
    "Computer Hardware",
    "Computer Hardware Manufacturing",
    "Computer Networking",
    "Computer Networking Products",
    "Computer Software",
    "Computer and Network Security",
    "Computers and Electronics Manufacturing",
    "Conservation Programs",
    "Construction",
    "Construction Hardware Manufacturing",
    "Consumer Electronics",
    "Consumer Goods",
    "Consumer Goods Rental",
    "Consumer Services",
    "Correctional Institutions",
    "Cosmetics",
    "Cosmetology and Barber Schools",
    "Courts of Law",
    "Credit Intermediation",
    "Cutlery and Handtool Manufacturing",
    "Dairy",
    "Dairy Product Manufacturing",
    "Dance Companies",
    "Data Infrastructure and Analytics",
    "Data Security Software Products",
    "Death Care Services",
    "Defense and Space",
    "Defense and Space Manufacturing",
    "Dentists",
    "Design",
    "Design Services",
    "Desktop Computing Software Products",
    "Digital Accessibility Services",
    "Distilleries",
    "E-Learning Providers",
    "E-learning",
    "Economic Programs",
    "Education",
    "Education Administration Programs",
    "Education Management",
    "Electric Lighting Equipment Manufacturing",
    "Electric Power Generation",
    "Electric Power Transmission; Control; and Distribution",
    "Electrical Equipment Manufacturing",
    "Electrical and Electronic Manufacturing",
    "Electronic and Precision Equipment Maintenance",
    "Embedded Software Products",
    "Emergency and Relief Services",
    "Energy Technology",
    "Engineering Services",
    "Engines and Power Transmission Equipment Manufacturing",
    "Entertainment",
    "Entertainment Providers",
    "Environmental Quality Programs",
    "Environmental Services",
    "Equipment Rental Services",
    "Events Services",
    "Executive Office",
    "Executive Offices",
    "Executive Search Services",
    "Fabricated Metal Products",
    "Facilities Services",
    "Family Planning Centers",
    "Farming",
    "Farming; Ranching; Forestry",
    "Fashion Accessories Manufacturing",
    "Financial Services",
    "Fine Art",
    "Fine Arts Schools",
    "Fire Protection",
    "Fisheries",
    "Fishery",
    "Flight Training",
    "Food Production",
    "Food and Beverage Manufacturing",
    "Food and Beverage Retail",
    "Food and Beverage Services",
    "Food and Beverages",
    "Footwear Manufacturing",
    "Footwear and Leather Goods Repair",
    "Forestry and Logging",
    "Fossil Fuel Electric Power Generation",
    "Freight and Package Transportation",
    "Fruit and Vegetable Preserves Manufacturing",
    "Fuel Cell Manufacturing",
    "Fundraising",
    "Funds and Trusts",
    "Funeral Services",
    "Furniture",
    "Furniture and Home Furnishings Manufacturing",
    "Gambling Facilities and Casinos",
    "Gambling and Casinos",
    "Geothermal Electric Power Generation",
    "Glass Product Manufacturing",
    "Glass; Ceramics and Concrete",
    "Glass; Ceramics and Concrete Manufacturing",
    "Golf Courses and Country Clubs",
    "Government Administration",
    "Government Relations",
    "Government Relations Services",
    "Graphic Design",
    "Ground Passenger Transportation",
    "HVAC and Refrigeration Equipment Manufacturing",
    "Health and Human Services",
    "Health; Wellness and Fitness",
    "Higher Education",
    "Highway; Street; and Bridge Construction",
    "Historical Sites",
    "Holding Companies",
    "Home Health Care Services",
    "Horticulture",
    "Hospital and Health Care",
    "Hospitality",
    "Hospitals",
    "Hospitals and Health Care",
    "Hotels and Motels",
    "Household Appliance Manufacturing",
    "Household Services",
    "Household and Institutional Furniture Manufacturing",
    "Housing Programs",
    "Housing and Community Development",
    "Human Resources",
    "Human Resources Services",
    "Hydroelectric Power Generation",
    "IT Services and IT Consulting",
    "IT System Custom Software Development",
    "IT System Data Services",
    "IT System Design Services",
    "IT System Installation and Disposal",
    "IT System Operations and Maintenance",
    "IT System Testing and Evaluation",
    "IT System Training and Support",
    "Import and Export",
    "Individual and Family Services",
    "Industrial Automation",
    "Industrial Machinery Manufacturing",
    "Industry Associations",
    "Information Services",
    "Information Technology and Services",
    "Insurance",
    "Insurance Agencies and Brokerages",
    "Insurance Carriers",
    "Insurance and Employee Benefit Funds",
    "Interior Design",
    "International Affairs",
    "International Trade and Development",
    "Internet",
    "Internet Marketplace Platforms",
    "Internet News",
    "Internet Publishing",
    "Interurban and Rural Bus Services",
    "Investment Advice",
    "Investment Banking",
    "Investment Management",
    "Janitorial Services",
    "Judiciary",
    "Landscaping Services",
    "Language Schools",
    "Laundry and Drycleaning Services",
    "Law Enforcement",
    "Law Practice",
    "Leasing Non-residential Real Estate",
    "Leasing Residential Real Estate",
    "Leather Product Manufacturing",
    "Legal Services",
    "Legislative Offices",
    "Leisure; Travel and Tourism",
    "Libraries",
    "Lime and Gypsum Products Manufacturing",
    "Loan Brokers",
    "Logistics and Supply Chain",
    "Luxury Goods and Jewelry",
    "Machinery",
    "Machinery Manufacturing",
    "Magnetic and Optical Media Manufacturing",
    "Management Consulting",
    "Manufacturing",
    "Maritime",
    "Maritime Transportation",
    "Market Research",
    "Marketing Services",
    "Marketing and Advertising",
    "Mattress and Blinds Manufacturing",
    "Measuring and Control Instrument Manufacturing",
    "Meat Products Manufacturing",
    "Mechanical Or Industrial Engineering",
    "Media Production",
    "Media and Telecommunications",
    "Medical Device",
    "Medical Equipment Manufacturing",
    "Medical Practice",
    "Medical Practices",
    "Medical and Diagnostic Laboratories",
    "Mental Health Care",
    "Metal Ore Mining",
    "Metal Treatments",
    "Metal Valve; Ball; and Roller Manufacturing",
    "Metalworking Machinery Manufacturing",
    "Military",
    "Military and International Affairs",
    "Mining",
    "Mining and Metals",
    "Mobile Computing Software Products",
    "Mobile Food Services",
    "Mobile Games",
    "Mobile Gaming Apps",
    "Motion Pictures and Film",
    "Motor Vehicle Manufacturing",
    "Motor Vehicle Parts Manufacturing",
    "Movies and Sound Recording",
    "Movies; Videos; and Sound",
    "Museums",
    "Museums and Institutions",
    "Museums; Historical Sites; and Zoos",
    "Music",
    "Musicians",
    "Nanotechnology",
    "Nanotechnology Research",
    "Natural Gas Distribution",
    "Natural Gas Extraction",
    "Newspaper Publishing",
    "Newspapers",
    "Non-profit Organization Management",
    "Non-profit Organizations",
    "Nonmetallic Mineral Mining",
    "Nonresidential Building Construction",
    "Nuclear Electric Power Generation",
    "Nursing Homes and Residential Care Facilities",
    "Office Administration",
    "Office Furniture and Fixtures Manufacturing",
    "Oil Extraction",
    "Oil and Coal Product Manufacturing",
    "Oil and Energy",
    "Oil and Gas",
    "Oil; Gas; and Mining",
    "Online Audio and Video Media",
    "Online Media",
    "Online and Mail Order Retail",
    "Operations Consulting",
    "Optometrists",
    "Other",
    "Outpatient Care Centers",
    "Outsourcing and Offshoring Consulting",
    "Outsourcing/Offshoring",
    "Package/Freight Delivery",
    "Packaging and Containers",
    "Packaging and Containers Manufacturing",
    "Paint; Coating; and Adhesive Manufacturing",
    "Paper and Forest Product Manufacturing",
    "Paper and Forest Products",
    "Parts Distribution",
    "Pension Funds",
    "Performing Arts",
    "Performing Arts and Spectator Sports",
    "Periodical Publishing",
    "Personal Care Product Manufacturing",
    "Personal Care Services",
    "Personal and Laundry Services",
    "Pet Services",
    "Pharmaceutical Manufacturing",
    "Pharmaceuticals",
    "Philanthropic Fundraising Services",
    "Philanthropy",
    "Photography",
    "Physical; Occupational and Speech Therapists",
    "Physicians",
    "Pipeline Transportation",
    "Plastics",
    "Plastics Manufacturing",
    "Plastics and Rubber Product Manufacturing",
    "Political Organization",
    "Political Organizations",
    "Postal Services",
    "Primary Metal Manufacturing",
    "Primary and Secondary Education",
    "Primary/Secondary Education",
    "Printing",
    "Printing Services",
    "Professional Organizations",
    "Professional Services",
    "Professional Training and Coaching",
    "Program Development",
    "Public Assistance Programs",
    "Public Health",
    "Public Policy",
    "Public Policy Offices",
    "Public Relations and Communications",
    "Public Relations and Communications Services",
    "Public Safety",
    "Public Works",
    "Publishing",
    "Racetracks",
    "Radio and Television Broadcasting",
    "Rail Transportation",
    "Railroad Equipment Manufacturing",
    "Railroad Manufacture",
    "Ranching",
    "Ranching and Fisheries",
    "Real Estate",
    "Real Estate Agents and Brokers",
    "Real Estate and Equipment Rental Services",
    "Recreational Facilities",
    "Recreational Facilities and Services",
    "Regenerative Design",
    "Religious Institutions",
    "Renewable Energy Equipment Manufacturing",
    "Renewable Energy Power Generation",
    "Renewable Energy Semiconductor Manufacturing",
    "Renewables and Environment",
    "Repair and Maintenance",
    "Research",
    "Research Services",
    "Residential Building Construction",
    "Restaurants",
    "Retail",
    "Retail Apparel and Fashion",
    "Retail Appliances; Electrical; and Electronic Equipment",
    "Retail Art Dealers",
    "Retail Art Supplies",
    "Retail Books and Printed News",
    "Retail Building Materials and Garden Equipment",
    "Retail Florists",
    "Retail Furniture and Home Furnishings",
    "Retail Gasoline",
    "Retail Groceries",
    "Retail Health and Personal Care Products",
    "Retail Luxury Goods and Jewelry",
    "Retail Motor Vehicles",
    "Retail Musical Instruments",
    "Retail Office Equipment",
    "Retail Office Supplies and Gifts",
    "Retail Pharmacies",
    "Retail Recyclable Materials and Used Merchandise",
    "Reupholstery and Furniture Repair",
    "Robot Manufacturing",
    "Robotics Engineering",
    "Rubber Products Manufacturing",
    "Satellite Telecommunications",
    "Savings Institutions",
    "School and Employee Bus Services",
    "Seafood Product Manufacturing",
    "Secretarial Schools",
    "Securities and Commodity Exchanges",
    "Security Guards and Patrol Services",
    "Security Systems Services",
    "Security and Investigations",
    "Semiconductor Manufacturing",
    "Semiconductors",
    "Services for Renewable Energy",
    "Services for the Elderly and Disabled",
    "Sheet Music Publishing",
    "Shipbuilding",
    "Shuttles and Special Needs Transportation Services",
    "Sightseeing Transportation",
    "Skiing Facilities",
    "Smart Meter Manufacturing",
    "Soap and Cleaning Product Manufacturing",
    "Social Networking Platforms",
    "Software Development",
    "Solar Electric Power Generation",
    "Sound Recording",
    "Space Research and Technology",
    "Specialty Trade Contractors",
    "Spectator Sports",
    "Sporting Goods",
    "Sporting Goods Manufacturing",
    "Sports",
    "Sports Teams and Clubs",
    "Sports and Recreation Instruction",
    "Spring and Wire Product Manufacturing",
    "Staffing and Recruiting",
    "Steam and Air-Conditioning Supply",
    "Strategic Management Services",
    "Subdivision of Land",
    "Sugar and Confectionery Product Manufacturing",
    "Supermarkets",
    "Surveying and Mapping Services",
    "Taxi and Limousine Services",
    "Technical and Vocational Training",
    "Technology; Information and Internet",
    "Technology; Information and Media",
    "Telecommunications",
    "Telecommunications Carriers",
    "Telephone Call Centers",
    "Temporary Help Services",
    "Textile Manufacturing",
    "Textiles",
    "Theater Companies",
    "Think Tanks",
    "Tobacco",
    "Tobacco Manufacturing",
    "Translation and Localization",
    "Transportation Equipment Manufacturing",
    "Transportation Programs",
    "Transportation/Trucking/Railroad",
    "Transportation; Logistics; Supply Chain and Storage",
    "Travel Arrangements",
    "Truck Transportation",
    "Trusts and Estates",
    "Turned Products and Fastener Manufacturing",
    "Urban Transit Services",
    "Utilities",
    "Utilities Administration",
    "Utility System Construction",
    "Vehicle Repair and Maintenance",
    "Venture Capital and Private Equity",
    "Venture Capital and Private Equity Principals",
    "Veterinary",
    "Veterinary Services",
    "Vocational Rehabilitation Services",
    "Warehousing",
    "Warehousing and Storage",
    "Waste Collection",
    "Waste Treatment and Disposal",
    "Water Supply and Irrigation Systems",
    "Water; Waste; Steam; and Air Conditioning Services",
    "Wellness and Fitness Services",
    "Wholesale",
    "Wholesale Alcoholic Beverages",
    "Wholesale Apparel and Sewing Supplies",
    "Wholesale Appliances; Electrical; and Electronics",
    "Wholesale Building Materials",
    "Wholesale Chemical and Allied Products",
    "Wholesale Computer Equipment",
    "Wholesale Drugs and Sundries",
    "Wholesale Food and Beverage",
    "Wholesale Footwear",
    "Wholesale Furniture and Home Furnishings",
    "Wholesale Hardware; Plumbing; Heating Equipment",
    "Wholesale Import and Export",
    "Wholesale Luxury Goods and Jewelry",
    "Wholesale Machinery",
    "Wholesale Metals and Minerals",
    "Wholesale Motor Vehicles and Parts",
    "Wholesale Paper Products",
    "Wholesale Petroleum and Petroleum Products",
    "Wholesale Photography Equipment and Supplies",
    "Wholesale Raw Farm Products",
    "Wholesale Recyclable Materials",
    "Wind Electric Power Generation",
    "Wine and Spirits",
    "Wineries",
    "Wireless",
    "Wireless Services",
    "Women's Handbag Manufacturing",
    "Wood Product Manufacturing",
    "Writing and Editing",
    "Zoos and Botanical Gardens",
)

BLITZAPI_EMPLOYEE_RANGES: tuple[str, ...] = (
    "1-10",
    "11-50",
    "51-200",
    "201-500",
    "501-1000",
    "1001-5000",
    "5001-10000",
    "10001+",
)

BLITZAPI_COMPANY_TYPES: tuple[str, ...] = (
    "Educational",
    "Educational Institution",
    "Government Agency",
    "Nonprofit",
    "Partnership",
    "Privately Held",
    "Public Company",
    "Self-Employed",
    "Self-Owned",
    "Sole Proprietorship",
)

BLITZAPI_CONTINENTS: tuple[str, ...] = (
    "Africa",
    "Antarctica",
    "Asia",
    "Europe",
    "North America",
    "Oceania",
    "South America",
)

BLITZAPI_SALES_REGIONS: tuple[str, ...] = (
    "NORAM",
    "LATAM",
    "EMEA",
    "APAC",
)

BLITZAPI_COUNTRY_CODES: tuple[str, ...] = (
    "AU",
    "BR",
    "CA",
    "DE",
    "FR",
    "GB",
    "IN",
    "SG",
    "US",
    "WORLD",
)

# ---------------------------------------------------------------------------
# Reverse lookup dicts (lowercase → original casing)
# Used by the resolver for exact matching and fuzzy match reverse-mapping.
# ---------------------------------------------------------------------------

_PROSPEO_SENIORITIES_LOOKUP = {v.lower(): v for v in PROSPEO_SENIORITIES}
_PROSPEO_DEPARTMENTS_LOOKUP = {v.lower(): v for v in PROSPEO_DEPARTMENTS}
_PROSPEO_INDUSTRIES_LOOKUP = {v.lower(): v for v in PROSPEO_INDUSTRIES}
_PROSPEO_EMPLOYEE_RANGES_LOOKUP = {v.lower(): v for v in PROSPEO_EMPLOYEE_RANGES}

_BLITZAPI_JOB_LEVELS_LOOKUP = {v.lower(): v for v in BLITZAPI_JOB_LEVELS}
_BLITZAPI_JOB_FUNCTIONS_LOOKUP = {v.lower(): v for v in BLITZAPI_JOB_FUNCTIONS}
_BLITZAPI_INDUSTRIES_LOOKUP = {v.lower(): v for v in BLITZAPI_INDUSTRIES}
_BLITZAPI_EMPLOYEE_RANGES_LOOKUP = {v.lower(): v for v in BLITZAPI_EMPLOYEE_RANGES}
_BLITZAPI_COMPANY_TYPES_LOOKUP = {v.lower(): v for v in BLITZAPI_COMPANY_TYPES}
_BLITZAPI_CONTINENTS_LOOKUP = {v.lower(): v for v in BLITZAPI_CONTINENTS}
_BLITZAPI_SALES_REGIONS_LOOKUP = {v.lower(): v for v in BLITZAPI_SALES_REGIONS}
_BLITZAPI_COUNTRY_CODES_LOOKUP = {v.lower(): v for v in BLITZAPI_COUNTRY_CODES}

# ---------------------------------------------------------------------------
# Registry mapping: (provider, field) → (values, lookup)
# Used by the resolver to avoid hard-coding provider/field → constant mappings.
# ---------------------------------------------------------------------------

VALUES_REGISTRY: dict[tuple[str, str], tuple[tuple[str, ...], dict[str, str]]] = {
    ("prospeo", "seniority"): (PROSPEO_SENIORITIES, _PROSPEO_SENIORITIES_LOOKUP),
    ("prospeo", "department"): (PROSPEO_DEPARTMENTS, _PROSPEO_DEPARTMENTS_LOOKUP),
    ("prospeo", "industry"): (PROSPEO_INDUSTRIES, _PROSPEO_INDUSTRIES_LOOKUP),
    ("prospeo", "employee_range"): (PROSPEO_EMPLOYEE_RANGES, _PROSPEO_EMPLOYEE_RANGES_LOOKUP),
    ("blitzapi", "seniority"): (BLITZAPI_JOB_LEVELS, _BLITZAPI_JOB_LEVELS_LOOKUP),
    ("blitzapi", "department"): (BLITZAPI_JOB_FUNCTIONS, _BLITZAPI_JOB_FUNCTIONS_LOOKUP),
    ("blitzapi", "industry"): (BLITZAPI_INDUSTRIES, _BLITZAPI_INDUSTRIES_LOOKUP),
    ("blitzapi", "employee_range"): (BLITZAPI_EMPLOYEE_RANGES, _BLITZAPI_EMPLOYEE_RANGES_LOOKUP),
    ("blitzapi", "company_type"): (BLITZAPI_COMPANY_TYPES, _BLITZAPI_COMPANY_TYPES_LOOKUP),
    ("blitzapi", "continent"): (BLITZAPI_CONTINENTS, _BLITZAPI_CONTINENTS_LOOKUP),
    ("blitzapi", "sales_region"): (BLITZAPI_SALES_REGIONS, _BLITZAPI_SALES_REGIONS_LOOKUP),
    ("blitzapi", "country_code"): (BLITZAPI_COUNTRY_CODES, _BLITZAPI_COUNTRY_CODES_LOOKUP),
}
