BEGIN;

CREATE TABLE IF NOT EXISTS entities.sam_gov_entities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- SAM.gov extract columns (368 positional fields)
    unique_entity_id TEXT,
    col_002_deprecated TEXT,
    entity_eft_indicator TEXT,
    cage_code TEXT,
    dodaac TEXT,
    sam_extract_code TEXT,
    purpose_of_registration TEXT,
    initial_registration_date TEXT,
    registration_expiration_date TEXT,
    last_update_date TEXT,
    activation_date TEXT,
    legal_business_name TEXT,
    dba_name TEXT,
    entity_division_name TEXT,
    entity_division_number TEXT,
    physical_address_line_1 TEXT,
    physical_address_line_2 TEXT,
    physical_address_city TEXT,
    physical_address_province_or_state TEXT,
    physical_address_zippostal_code TEXT,
    physical_address_zip_code_4 TEXT,
    physical_address_country_code TEXT,
    physical_address_congressional_district TEXT,
    db_open_data_flag TEXT,
    entity_start_date TEXT,
    fiscal_year_end_close_date TEXT,
    company_security_level TEXT,
    highest_employee_security_level TEXT,
    entity_url TEXT,
    entity_structure TEXT,
    state_of_incorporation TEXT,
    country_of_incorporation TEXT,
    business_type_counter TEXT,
    bus_type_string TEXT,
    agency_business_purpose TEXT,
    primary_naics TEXT,
    naics_code_counter TEXT,
    naics_code_string TEXT,
    psc_code_counter TEXT,
    psc_code_string TEXT,
    credit_card_usage TEXT,
    correspondence_flag TEXT,
    mailing_address_line_1 TEXT,
    mailing_address_line_2 TEXT,
    mailing_address_city TEXT,
    mailing_address_zippostal_code TEXT,
    mailing_address_zip_code_4 TEXT,
    mailing_address_country TEXT,
    mailing_address_state_or_province TEXT,
    govt_bus_poc_first_name TEXT,
    govt_bus_poc_middle_initial TEXT,
    govt_bus_poc_last_name TEXT,
    govt_bus_poc_title TEXT,
    govt_bus_poc_st_add_1 TEXT,
    govt_bus_poc_st_add_2 TEXT,
    govt_bus_poc_city TEXT,
    govt_bus_poc_zippostal_code TEXT,
    govt_bus_poc_zip_code_4 TEXT,
    govt_bus_poc_country_code TEXT,
    govt_bus_poc_state_or_province TEXT,
    govt_bus_poc_us_phone TEXT,
    govt_bus_poc_us_phone_ext TEXT,
    govt_bus_poc_nonus_phone TEXT,
    govt_bus_poc_fax_us_only TEXT,
    govt_bus_poc_email TEXT,
    alt_govt_bus_poc_first_name TEXT,
    alt_govt_bus_poc_middle_initial TEXT,
    alt_govt_bus_poc_last_name TEXT,
    alt_govt_bus_poc_title TEXT,
    alt_govt_bus_poc_st_add_1 TEXT,
    alt_govt_bus_poc_st_add_2 TEXT,
    alt_govt_bus_poc_city TEXT,
    alt_govt_bus_poc_zippostal_code TEXT,
    alt_govt_bus_poc_zip_code_4 TEXT,
    alt_govt_bus_poc_country_code TEXT,
    alt_govt_bus_poc_state_or_province TEXT,
    alt_govt_bus_poc_us_phone TEXT,
    alt_govt_bus_poc_us_phone_ext TEXT,
    alt_govt_bus_poc_nonus_phone TEXT,
    alt_govt_bus_poc_fax_us_only TEXT,
    alt_govt_bus_poc_email TEXT,
    past_perf_poc_poc_first_name TEXT,
    past_perf_poc_poc_middle_initial TEXT,
    past_perf_poc_poc_last_name TEXT,
    past_perf_poc_poc_title TEXT,
    past_perf_poc_st_add_1 TEXT,
    past_perf_poc_st_add_2 TEXT,
    past_perf_poc_city TEXT,
    past_perf_poc_zippostal_code TEXT,
    past_perf_poc_zip_code_4 TEXT,
    past_perf_poc_country_code TEXT,
    past_perf_poc_state_or_province TEXT,
    past_perf_poc_us_phone TEXT,
    past_perf_poc_us_phone_ext TEXT,
    past_perf_poc_nonus_phone TEXT,
    past_perf_poc_fax_us_only TEXT,
    past_perf_poc_email TEXT,
    alt_past_perf_poc_first_name TEXT,
    alt_past_perf_poc_middle_initial TEXT,
    alt_past_perf_poc_last_name TEXT,
    alt_past_perf_poc_title TEXT,
    alt_past_perf_poc_st_add_1 TEXT,
    alt_past_perf_poc_st_add_2 TEXT,
    alt_past_perf_poc_city TEXT,
    alt_past_perf_poc_zippostal_code TEXT,
    alt_past_perf_poc_zip_code_4 TEXT,
    alt_past_perf_poc_country_code TEXT,
    alt_past_perf_poc_state_or_province TEXT,
    alt_past_perf_poc_us_phone TEXT,
    alt_past_perf_poc_us_phone_ext TEXT,
    alt_past_perf_poc_nonus_phone TEXT,
    alt_past_perf_poc_fax_us_only TEXT,
    alt_past_perf_poc_email TEXT,
    elec_bus_poc_first_name TEXT,
    elec_bus_poc_middle_initial TEXT,
    elec_bus_poc_last_name TEXT,
    elec_bus_poc_title TEXT,
    elec_bus_poc_st_add_1 TEXT,
    elec_bus_poc_st_add_2 TEXT,
    elec_bus_poc_city TEXT,
    elec_bus_poc_zippostal_code TEXT,
    elec_bus_poc_zip_code_4 TEXT,
    elec_bus_poc_country_code TEXT,
    elec_bus_poc_state_or_province TEXT,
    elec_bus_poc_us_phone TEXT,
    elec_bus_poc_us_phone_ext TEXT,
    elec_bus_poc_nonus_phone TEXT,
    elec_bus_poc_fax_us_only TEXT,
    elec_bus_poc_email TEXT,
    alt_elec_poc_bus_poc_first_name TEXT,
    alt_elec_poc_bus_poc_middle_initial TEXT,
    alt_elec_poc_bus_poc_last_name TEXT,
    alt_elec_poc_bus_poc_title TEXT,
    alt_elec_poc_bus_st_add_1 TEXT,
    alt_elec_poc_bus_st_add_2 TEXT,
    alt_elec_poc_bus_city TEXT,
    alt_elec_poc_bus_zippostal_code TEXT,
    alt_elec_poc_bus_zip_code_4 TEXT,
    alt_elec_poc_bus_country_code TEXT,
    alt_elec_poc_bus_state_or_province TEXT,
    alt_elec_poc_bus_us_phone TEXT,
    alt_elec_poc_bus_us_phone_ext TEXT,
    alt_elec_poc_bus_nonus_phone TEXT,
    alt_elec_poc_bus_fax_us_only TEXT,
    alt_elec_poc_bus_email TEXT,
    party_performing_certification_poc_first_name TEXT,
    party_performing_certification_poc_middle_initial TEXT,
    party_performing_certification_poc_last_name TEXT,
    party_performing_certification_poc_title TEXT,
    party_performing_certification_poc_bus_st_add_1 TEXT,
    party_performing_certification_poc_bus_st_add_2 TEXT,
    party_performing_certification_poc_bus_city TEXT,
    party_performing_certification_poc_bus_zippostal_code TEXT,
    party_performing_certification_poc_bus_zip_code_4 TEXT,
    party_performing_certification_poc_bus_country_code TEXT,
    party_performing_certification_poc_bus_state_or_province TEXT,
    party_performing_certification_poc_us_phone TEXT,
    party_performing_certification_poc_us_phone_ext TEXT,
    party_performing_certification_poc_nonus_phone TEXT,
    party_performing_certification_poc_fax_us_only TEXT,
    party_performing_certification_poc_email TEXT,
    sole_proprietorship_poc_first_name TEXT,
    sole_proprietorship_poc_middle_initial TEXT,
    sole_proprietorship_poc_last_name TEXT,
    sole_proprietorship_poc_title TEXT,
    sole_proprietorship_poc_us_phone TEXT,
    sole_proprietorship_poc_us_phone_ext TEXT,
    sole_proprietorship_poc_nonus_phone TEXT,
    sole_proprietorship_poc_fax_us_only TEXT,
    sole_proprietorship_poc_email TEXT,
    immediate_parent_legal_business_name TEXT,
    immediate_parent_unique_entity_id TEXT,
    immediate_parent_st_add_1 TEXT,
    immediate_parent_st_add_2 TEXT,
    immediate_parent_city TEXT,
    immediate_parent_postal_code TEXT,
    immediate_parent_country_code TEXT,
    immediate_parent_state_or_province TEXT,
    immediate_parent_phone TEXT,
    hq_parent_legal_business_name TEXT,
    hq_parent_unique_entity_id TEXT,
    col_182_deprecated TEXT,
    hq_parent_st_add_1 TEXT,
    hq_parent_st_add_2 TEXT,
    hq_parent_city TEXT,
    hq_parent_postal_code TEXT,
    hq_parent_country_code TEXT,
    hq_parent_state_or_province TEXT,
    hq_parent_phone TEXT,
    domestic_parent_legal_business_name TEXT,
    domestic_parent_unique_entity_id TEXT,
    col_192_deprecated TEXT,
    domestic_parent_st_add_1 TEXT,
    domestic_parent_st_add_2 TEXT,
    domestic_parent_city TEXT,
    domestic_parent_postal_code TEXT,
    domestic_parent_country_code TEXT,
    domestic_parent_state_or_province TEXT,
    domestic_parent_phone TEXT,
    ultimate_parent_legal_business_name TEXT,
    ultimate_parent_unique_entity_id TEXT,
    col_202_deprecated TEXT,
    ultimate_parent_st_add_1 TEXT,
    ultimate_parent_st_add_2 TEXT,
    ultimate_parent_city TEXT,
    ultimate_parent_postal_code TEXT,
    ultimate_parent_country_code TEXT,
    ultimate_parent_state_or_province TEXT,
    ultimate_parent_phone TEXT,
    evs_out_of_business_indicator TEXT,
    evs_monitoring_last_updated TEXT,
    evs_monitoring_status TEXT,
    evs_monitoring_legal_business_name TEXT,
    evs_monitoring_dba TEXT,
    evs_monitoring_address_1 TEXT,
    evs_monitoring_address_2 TEXT,
    evs_monitoring_city TEXT,
    evs_monitoring_postal_code TEXT,
    evs_monitoring_country_code TEXT,
    evs_monitoring_state_or_province TEXT,
    edi TEXT,
    edi_van_provider TEXT,
    isa_qualifier TEXT,
    isa_identifier TEXT,
    functional_group_identifier TEXT,
    field_820s_request_flag TEXT,
    edi_poc_first_name TEXT,
    edi_poc_middle_initial TEXT,
    edi_poc_last_name TEXT,
    edi_poc_title TEXT,
    edi_poc_us_phone TEXT,
    edi_poc_us_phone_ext TEXT,
    edi_poc_nonus_phone TEXT,
    edi_poc_fax_us_only TEXT,
    edi_poc_email TEXT,
    tax_identifier_type TEXT,
    tax_identifier_number TEXT,
    average_number_of_employees TEXT,
    average_annual_revenue TEXT,
    financial_institute TEXT,
    account_number TEXT,
    aba_routing_id TEXT,
    account_type TEXT,
    lockbox_number TEXT,
    authorization_date TEXT,
    eft_waiver TEXT,
    ach_us_phone TEXT,
    ach_nonus_phone TEXT,
    ach_fax TEXT,
    ach_email TEXT,
    remittance_name TEXT,
    remittance_address_line_1 TEXT,
    remittance_address_line_2 TEXT,
    remittance_city TEXT,
    remittance_state_or_province TEXT,
    remittance_zippostal_code TEXT,
    remittance_zip_code_4 TEXT,
    remittance_country TEXT,
    accounts_receivable_poc_first_name TEXT,
    accounts_receivable_poc_middle_initial TEXT,
    accounts_receivable_poc_last_name TEXT,
    accounts_receivable_poc_title TEXT,
    accounts_receivable_poc_us_phone TEXT,
    accounts_receivable_poc_us_phone_ext TEXT,
    accounts_receivable_poc_nonus_phone TEXT,
    accounts_receivable_poc_fax_us_only TEXT,
    accounts_receivable_poc_email TEXT,
    accounts_payable_poc_first_name TEXT,
    accounts_payable_poc_middle_initial TEXT,
    accounts_payable_poc_last_name TEXT,
    accounts_payable_poc_title TEXT,
    accounts_payable_poc_st_add_1 TEXT,
    accounts_payable_poc_st_add_2 TEXT,
    accounts_payable_poc_city TEXT,
    accounts_payable_poc_zippostal_code TEXT,
    accounts_payable_poc_zip_code_4 TEXT,
    accounts_payable_poc_country_code TEXT,
    accounts_payable_poc_state_or_province TEXT,
    accounts_payable_poc_us_phone TEXT,
    accounts_payable_poc_us_phone_ext TEXT,
    accounts_payable_poc_nonus_phone TEXT,
    accounts_payable_poc_fax_us_only TEXT,
    accounts_payable_poc_email TEXT,
    mpin TEXT,
    naics_exception_counter TEXT,
    naics_exception_string TEXT,
    debt_subject_to_offset_flag TEXT,
    exclusion_status_flag TEXT,
    sba_business_types_counter TEXT,
    sba_business_types_string TEXT,
    sam_numerics_counter TEXT,
    sam_numerics_code_string TEXT,
    no_public_display_flag TEXT,
    disaster_response_counter TEXT,
    disaster_response_string TEXT,
    annual_igt_revenue TEXT,
    agency_location_code TEXT,
    disbursing_office_symbol TEXT,
    merchant_id_1 TEXT,
    merchant_id_2 TEXT,
    accounting_station TEXT,
    source TEXT,
    department_code TEXT,
    hierarchy_department_code TEXT,
    hierarchy_department_name TEXT,
    hierarchy_agency_code TEXT,
    hierarchy_agency_name TEXT,
    hierarchy_office_code TEXT,
    eliminations_poc_first_name TEXT,
    eliminations_poc_middle_initial TEXT,
    eliminations_poc_last_name TEXT,
    eliminations_poc_title TEXT,
    eliminations_poc_st_add_1 TEXT,
    eliminations_poc_st_add_2 TEXT,
    eliminations_poc_city TEXT,
    eliminations_poc_zippostal_code TEXT,
    eliminations_poc_zip_code_4 TEXT,
    eliminations_poc_country_code TEXT,
    eliminations_poc_state_or_province TEXT,
    eliminations_poc_us_phone TEXT,
    eliminations_poc_us_phone_ext TEXT,
    eliminations_poc_nonus_phone TEXT,
    eliminations_poc_fax_us_only TEXT,
    eliminations_poc_email TEXT,
    sales_poc_first_name TEXT,
    sales_poc_middle_initial TEXT,
    sales_poc_last_name TEXT,
    sales_poc_title TEXT,
    sales_poc_st_add_1 TEXT,
    sales_poc_st_add_2 TEXT,
    sales_poc_city TEXT,
    sales_poc_zippostal_code TEXT,
    sales_poc_zip_code_4 TEXT,
    sales_poc_country_code TEXT,
    sales_poc_state_or_province TEXT,
    sales_poc_us_phone TEXT,
    sales_poc_us_phone_ext TEXT,
    sales_poc_nonus_phone TEXT,
    sales_poc_fax_us_only TEXT,
    sales_poc_email TEXT,
    taxpayer_name TEXT,
    entity_evs_source TEXT,
    hq_parent_evs_source TEXT,
    domestic_parent_evs_source TEXT,
    ultimate_parent_evs_source TEXT,
    immediate_parent_evs_source TEXT,
    tin_type TEXT,
    tin_number TEXT,
    flex_field_06 TEXT,
    flex_field_07 TEXT,
    flex_field_08 TEXT,
    flex_field_09 TEXT,
    flex_field_10 TEXT,
    flex_field_11 TEXT,
    flex_field_12 TEXT,
    flex_field_13 TEXT,
    flex_field_14 TEXT,
    flex_field_15 TEXT,
    flex_field_16 TEXT,
    flex_field_17 TEXT,
    flex_field_18 TEXT,
    flex_field_19 TEXT,
    flex_field_20 TEXT,
    flex_field_21 TEXT,
    flex_field_22 TEXT,
    flex_field_23 TEXT,
    flex_field_24 TEXT,
    end_of_record_indicator TEXT,

    -- Extract metadata columns
    extract_date DATE NOT NULL,
    extract_type TEXT NOT NULL,
    extract_code TEXT,
    source_filename TEXT NOT NULL,
    source_provider TEXT NOT NULL DEFAULT 'sam_gov',
    source_download_url TEXT,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    row_position INTEGER NOT NULL,
    raw_source_row TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique constraint: one UEI per extract_date (upsert conflict target)
ALTER TABLE entities.sam_gov_entities
    ADD CONSTRAINT uq_sam_gov_entities_extract_date_uei
    UNIQUE (extract_date, unique_entity_id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sam_gov_entities_uei
    ON entities.sam_gov_entities(unique_entity_id);

CREATE INDEX IF NOT EXISTS idx_sam_gov_entities_extract_date
    ON entities.sam_gov_entities(extract_date DESC);

CREATE INDEX IF NOT EXISTS idx_sam_gov_entities_extract_code
    ON entities.sam_gov_entities(extract_code);

CREATE INDEX IF NOT EXISTS idx_sam_gov_entities_primary_naics
    ON entities.sam_gov_entities(primary_naics);

CREATE INDEX IF NOT EXISTS idx_sam_gov_entities_state
    ON entities.sam_gov_entities(physical_address_province_or_state);

CREATE INDEX IF NOT EXISTS idx_sam_gov_entities_legal_name
    ON entities.sam_gov_entities(legal_business_name text_pattern_ops);

-- updated_at trigger
DROP TRIGGER IF EXISTS update_sam_gov_entities_updated_at ON entities.sam_gov_entities;
CREATE TRIGGER update_sam_gov_entities_updated_at
    BEFORE UPDATE ON entities.sam_gov_entities
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Row Level Security
ALTER TABLE entities.sam_gov_entities ENABLE ROW LEVEL SECURITY;

COMMIT;
