BEGIN;

CREATE TABLE IF NOT EXISTS entities.usaspending_contracts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- USASpending CSV columns (297 fields)
    contract_transaction_unique_key TEXT,
    contract_award_unique_key TEXT,
    award_id_piid TEXT,
    modification_number TEXT,
    transaction_number TEXT,
    parent_award_agency_id TEXT,
    parent_award_agency_name TEXT,
    parent_award_id_piid TEXT,
    parent_award_modification_number TEXT,
    federal_action_obligation TEXT,
    total_dollars_obligated TEXT,
    total_outlayed_amount_for_overall_award TEXT,
    base_and_exercised_options_value TEXT,
    current_total_value_of_award TEXT,
    base_and_all_options_value TEXT,
    potential_total_value_of_award TEXT,
    disaster_emergency_fund_codes_for_overall_award TEXT,
    outlayed_amount_from_covid_19_supplementals_for_overall_award TEXT,
    obligated_amount_from_covid_19_supplementals_for_overall_award TEXT,
    outlayed_amount_from_iija_supplemental_for_overall_award TEXT,
    obligated_amount_from_iija_supplemental_for_overall_award TEXT,
    action_date TEXT,
    action_date_fiscal_year TEXT,
    period_of_performance_start_date TEXT,
    period_of_performance_current_end_date TEXT,
    period_of_performance_potential_end_date TEXT,
    ordering_period_end_date TEXT,
    solicitation_date TEXT,
    awarding_agency_code TEXT,
    awarding_agency_name TEXT,
    awarding_sub_agency_code TEXT,
    awarding_sub_agency_name TEXT,
    awarding_office_code TEXT,
    awarding_office_name TEXT,
    funding_agency_code TEXT,
    funding_agency_name TEXT,
    funding_sub_agency_code TEXT,
    funding_sub_agency_name TEXT,
    funding_office_code TEXT,
    funding_office_name TEXT,
    treasury_accounts_funding_this_award TEXT,
    federal_accounts_funding_this_award TEXT,
    object_classes_funding_this_award TEXT,
    program_activities_funding_this_award TEXT,
    foreign_funding TEXT,
    foreign_funding_description TEXT,
    sam_exception TEXT,
    sam_exception_description TEXT,
    recipient_uei TEXT,
    recipient_duns TEXT,
    recipient_name TEXT,
    recipient_name_raw TEXT,
    recipient_doing_business_as_name TEXT,
    cage_code TEXT,
    recipient_parent_uei TEXT,
    recipient_parent_duns TEXT,
    recipient_parent_name TEXT,
    recipient_parent_name_raw TEXT,
    recipient_country_code TEXT,
    recipient_country_name TEXT,
    recipient_address_line_1 TEXT,
    recipient_address_line_2 TEXT,
    recipient_city_name TEXT,
    prime_award_transaction_recipient_county_fips_code TEXT,
    recipient_county_name TEXT,
    prime_award_transaction_recipient_state_fips_code TEXT,
    recipient_state_code TEXT,
    recipient_state_name TEXT,
    recipient_zip_4_code TEXT,
    prime_award_transaction_recipient_cd_original TEXT,
    prime_award_transaction_recipient_cd_current TEXT,
    recipient_phone_number TEXT,
    recipient_fax_number TEXT,
    primary_place_of_performance_country_code TEXT,
    primary_place_of_performance_country_name TEXT,
    primary_place_of_performance_city_name TEXT,
    prime_award_transaction_place_of_performance_county_fips_code TEXT,
    primary_place_of_performance_county_name TEXT,
    prime_award_transaction_place_of_performance_state_fips_code TEXT,
    primary_place_of_performance_state_code TEXT,
    primary_place_of_performance_state_name TEXT,
    primary_place_of_performance_zip_4 TEXT,
    prime_award_transaction_place_of_performance_cd_original TEXT,
    prime_award_transaction_place_of_performance_cd_current TEXT,
    award_or_idv_flag TEXT,
    award_type_code TEXT,
    award_type TEXT,
    idv_type_code TEXT,
    idv_type TEXT,
    multiple_or_single_award_idv_code TEXT,
    multiple_or_single_award_idv TEXT,
    type_of_idc_code TEXT,
    type_of_idc TEXT,
    type_of_contract_pricing_code TEXT,
    type_of_contract_pricing TEXT,
    transaction_description TEXT,
    prime_award_base_transaction_description TEXT,
    action_type_code TEXT,
    action_type TEXT,
    solicitation_identifier TEXT,
    number_of_actions TEXT,
    inherently_governmental_functions TEXT,
    inherently_governmental_functions_description TEXT,
    product_or_service_code TEXT,
    product_or_service_code_description TEXT,
    contract_bundling_code TEXT,
    contract_bundling TEXT,
    dod_claimant_program_code TEXT,
    dod_claimant_program_description TEXT,
    naics_code TEXT,
    naics_description TEXT,
    recovered_materials_sustainability_code TEXT,
    recovered_materials_sustainability TEXT,
    domestic_or_foreign_entity_code TEXT,
    domestic_or_foreign_entity TEXT,
    dod_acquisition_program_code TEXT,
    dod_acquisition_program_description TEXT,
    information_technology_commercial_item_category_code TEXT,
    information_technology_commercial_item_category TEXT,
    epa_designated_product_code TEXT,
    epa_designated_product TEXT,
    country_of_product_or_service_origin_code TEXT,
    country_of_product_or_service_origin TEXT,
    place_of_manufacture_code TEXT,
    place_of_manufacture TEXT,
    subcontracting_plan_code TEXT,
    subcontracting_plan TEXT,
    extent_competed_code TEXT,
    extent_competed TEXT,
    solicitation_procedures_code TEXT,
    solicitation_procedures TEXT,
    type_of_set_aside_code TEXT,
    type_of_set_aside TEXT,
    evaluated_preference_code TEXT,
    evaluated_preference TEXT,
    research_code TEXT,
    research TEXT,
    fair_opportunity_limited_sources_code TEXT,
    fair_opportunity_limited_sources TEXT,
    other_than_full_and_open_competition_code TEXT,
    other_than_full_and_open_competition TEXT,
    number_of_offers_received TEXT,
    commercial_item_acquisition_procedures_code TEXT,
    commercial_item_acquisition_procedures TEXT,
    small_business_competitiveness_demonstration_program TEXT,
    simplified_procedures_for_certain_commercial_items_code TEXT,
    simplified_procedures_for_certain_commercial_items TEXT,
    a76_fair_act_action_code TEXT,
    a76_fair_act_action TEXT,
    fed_biz_opps_code TEXT,
    fed_biz_opps TEXT,
    local_area_set_aside_code TEXT,
    local_area_set_aside TEXT,
    price_evaluation_adjustment_preference_percent_difference TEXT,
    clinger_cohen_act_planning_code TEXT,
    clinger_cohen_act_planning TEXT,
    materials_supplies_articles_equipment_code TEXT,
    materials_supplies_articles_equipment TEXT,
    labor_standards_code TEXT,
    labor_standards TEXT,
    construction_wage_rate_requirements_code TEXT,
    construction_wage_rate_requirements TEXT,
    interagency_contracting_authority_code TEXT,
    interagency_contracting_authority TEXT,
    other_statutory_authority TEXT,
    program_acronym TEXT,
    parent_award_type_code TEXT,
    parent_award_type TEXT,
    parent_award_single_or_multiple_code TEXT,
    parent_award_single_or_multiple TEXT,
    major_program TEXT,
    national_interest_action_code TEXT,
    national_interest_action TEXT,
    cost_or_pricing_data_code TEXT,
    cost_or_pricing_data TEXT,
    cost_accounting_standards_clause_code TEXT,
    cost_accounting_standards_clause TEXT,
    government_furnished_property_code TEXT,
    government_furnished_property TEXT,
    sea_transportation_code TEXT,
    sea_transportation TEXT,
    undefinitized_action_code TEXT,
    undefinitized_action TEXT,
    consolidated_contract_code TEXT,
    consolidated_contract TEXT,
    performance_based_service_acquisition_code TEXT,
    performance_based_service_acquisition TEXT,
    multi_year_contract_code TEXT,
    multi_year_contract TEXT,
    contract_financing_code TEXT,
    contract_financing TEXT,
    purchase_card_as_payment_method_code TEXT,
    purchase_card_as_payment_method TEXT,
    contingency_humanitarian_or_peacekeeping_operation_code TEXT,
    contingency_humanitarian_or_peacekeeping_operation TEXT,
    alaskan_native_corporation_owned_firm TEXT,
    american_indian_owned_business TEXT,
    indian_tribe_federally_recognized TEXT,
    native_hawaiian_organization_owned_firm TEXT,
    tribally_owned_firm TEXT,
    veteran_owned_business TEXT,
    service_disabled_veteran_owned_business TEXT,
    woman_owned_business TEXT,
    women_owned_small_business TEXT,
    economically_disadvantaged_women_owned_small_business TEXT,
    joint_venture_women_owned_small_business TEXT,
    joint_venture_economic_disadvantaged_women_owned_small_bus TEXT,
    minority_owned_business TEXT,
    subcontinent_asian_asian_indian_american_owned_business TEXT,
    asian_pacific_american_owned_business TEXT,
    black_american_owned_business TEXT,
    hispanic_american_owned_business TEXT,
    native_american_owned_business TEXT,
    other_minority_owned_business TEXT,
    contracting_officers_determination_of_business_size TEXT,
    contracting_officers_determination_of_business_size_code TEXT,
    emerging_small_business TEXT,
    community_developed_corporation_owned_firm TEXT,
    labor_surplus_area_firm TEXT,
    us_federal_government TEXT,
    federally_funded_research_and_development_corp TEXT,
    federal_agency TEXT,
    us_state_government TEXT,
    us_local_government TEXT,
    city_local_government TEXT,
    county_local_government TEXT,
    inter_municipal_local_government TEXT,
    local_government_owned TEXT,
    municipality_local_government TEXT,
    school_district_local_government TEXT,
    township_local_government TEXT,
    us_tribal_government TEXT,
    foreign_government TEXT,
    organizational_type TEXT,
    corporate_entity_not_tax_exempt TEXT,
    corporate_entity_tax_exempt TEXT,
    partnership_or_limited_liability_partnership TEXT,
    sole_proprietorship TEXT,
    small_agricultural_cooperative TEXT,
    international_organization TEXT,
    us_government_entity TEXT,
    community_development_corporation TEXT,
    domestic_shelter TEXT,
    educational_institution TEXT,
    foundation TEXT,
    hospital_flag TEXT,
    manufacturer_of_goods TEXT,
    veterinary_hospital TEXT,
    hispanic_servicing_institution TEXT,
    receives_contracts TEXT,
    receives_financial_assistance TEXT,
    receives_contracts_and_financial_assistance TEXT,
    airport_authority TEXT,
    council_of_governments TEXT,
    housing_authorities_public_tribal TEXT,
    interstate_entity TEXT,
    planning_commission TEXT,
    port_authority TEXT,
    transit_authority TEXT,
    subchapter_scorporation TEXT,
    limited_liability_corporation TEXT,
    foreign_owned TEXT,
    for_profit_organization TEXT,
    nonprofit_organization TEXT,
    other_not_for_profit_organization TEXT,
    the_ability_one_program TEXT,
    private_university_or_college TEXT,
    state_controlled_institution_of_higher_learning TEXT,
    col_1862_land_grant_college TEXT,
    col_1890_land_grant_college TEXT,
    col_1994_land_grant_college TEXT,
    minority_institution TEXT,
    historically_black_college TEXT,
    tribal_college TEXT,
    alaskan_native_servicing_institution TEXT,
    native_hawaiian_servicing_institution TEXT,
    school_of_forestry TEXT,
    veterinary_college TEXT,
    dot_certified_disadvantage TEXT,
    self_certified_small_disadvantaged_business TEXT,
    small_disadvantaged_business TEXT,
    c8a_program_participant TEXT,
    historically_underutilized_business_zone_hubzone_firm TEXT,
    sba_certified_8a_joint_venture TEXT,
    highly_compensated_officer_1_name TEXT,
    highly_compensated_officer_1_amount TEXT,
    highly_compensated_officer_2_name TEXT,
    highly_compensated_officer_2_amount TEXT,
    highly_compensated_officer_3_name TEXT,
    highly_compensated_officer_3_amount TEXT,
    highly_compensated_officer_4_name TEXT,
    highly_compensated_officer_4_amount TEXT,
    highly_compensated_officer_5_name TEXT,
    highly_compensated_officer_5_amount TEXT,
    usaspending_permalink TEXT,
    initial_report_date TEXT,
    last_modified_date TEXT,

    -- Delta-only columns (prepended in delta files)
    correction_delete_ind TEXT,
    agency_id TEXT,

    -- Extract metadata columns
    extract_date DATE NOT NULL,
    extract_type TEXT NOT NULL,
    source_filename TEXT NOT NULL,
    source_provider TEXT NOT NULL DEFAULT 'usaspending',
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    row_position INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique constraint
ALTER TABLE entities.usaspending_contracts
    ADD CONSTRAINT uq_usaspending_contracts_extract_date_txn_key
    UNIQUE (extract_date, contract_transaction_unique_key);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_usaspending_contracts_txn_key
    ON entities.usaspending_contracts(contract_transaction_unique_key);
CREATE INDEX IF NOT EXISTS idx_usaspending_contracts_award_key
    ON entities.usaspending_contracts(contract_award_unique_key);
CREATE INDEX IF NOT EXISTS idx_usaspending_contracts_recipient_uei
    ON entities.usaspending_contracts(recipient_uei);
CREATE INDEX IF NOT EXISTS idx_usaspending_contracts_action_date
    ON entities.usaspending_contracts(action_date);
CREATE INDEX IF NOT EXISTS idx_usaspending_contracts_awarding_agency
    ON entities.usaspending_contracts(awarding_agency_code);
CREATE INDEX IF NOT EXISTS idx_usaspending_contracts_naics
    ON entities.usaspending_contracts(naics_code);
CREATE INDEX IF NOT EXISTS idx_usaspending_contracts_extract_date
    ON entities.usaspending_contracts(extract_date DESC);

-- updated_at trigger
DROP TRIGGER IF EXISTS update_usaspending_contracts_updated_at ON entities.usaspending_contracts;
CREATE TRIGGER update_usaspending_contracts_updated_at
    BEFORE UPDATE ON entities.usaspending_contracts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Row Level Security
ALTER TABLE entities.usaspending_contracts ENABLE ROW LEVEL SECURITY;

COMMIT;
